lancedb/lancedb

docs/mkdocs.yml, docs/src/embedding.md, docs/src/index.md, docs/src/python.md
=> [DOC] embedding function documentation

python/lancedb/table.py, python/tests/test_table.py
=> expose methods to work with versioning in tables

docs/src/basic.md, python/lancedb/db.py, python/lancedb/table.py, python/tests/test_db.py
=> Add mode to overwrite table if already exists

docs/src/ann_indexes.md, python/lancedb/query.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_query.py
=> Make distance metric configurable in LanceDB

docs/src/ann_indexes.md, python/lancedb/query.py, python/lancedb/table.py
=> Add more detailed docs for the ANN index and search features

rust/Cargo.toml, rust/src/lib.rs
* Only place holder at the moment.
* Claimed the crate name
=> Rust core directory

docs/src/examples/nodejs.md
nodejs read only example, an adaptation of the youtube transcriptions example
=> nodejs read only example

.github/workflows/node.yml, Cargo.toml, node/native.js, node/package.json
=> Lint and test vectordb node in CI

python/lancedb/db.py, python/tests/test_db.py
=> [Python] Support drop table

.gitignore, docs/src/notebooks/multimodal_search.ipynb
=> add code snippet for each example

docs/src/examples/langchain.md, docs/src/examples/multimodal_search.md, docs/src/examples/youtube_transcript_search.md
closes #121 
adds new multimodal example to gallery app
=> Update broken doc links to refer to new directory and include gallery app for multimodal search

.github/workflows/python.yml, python/lancedb/fts.py, python/lancedb/query.py, python/pyproject.toml, python/tests/test_fts.py
=> Better handle empty results from tantivy

docs/src/embedding.md
Added missing tab to python snippet
=> [docs] Fixed Minor typo in embedding.md

python/lancedb/context.py, python/lancedb/exceptions.py
=> [Python] FIx Contextualizer validation to arguments

docs/mkdocs.yml, docs/overrides/partials/header.html, docs/src/integrations.md
Includes discord and twitter links in documentation
[#1001](https://github.com/lancedb/sophon/issues/1001)
=> [docs] CTA for discord + twitter

Cargo.lock, node/src/index.ts, node/src/test/test.ts, python/lancedb/db.py, python/lancedb/table.py, python/pyproject.toml, rust/ffi/node/Cargo.toml, rust/ffi/node/src/lib.rs, rust/vectordb/Cargo.toml, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs
Also upgrades Arrow and Lance.
=> feat: support for deletion

node/README.md, node/package-lock.json, node/package.json, node/src/index.ts, node/src/test/test.ts, rust/ffi/node/src/index/vector.rs
=> [Js] Create index with replace flag

python/lancedb/table.py, python/tests/test_db.py, python/tests/test_table.py
=> [Python] Support replace during create_index

Cargo.lock, rust/ffi/node/Cargo.toml, rust/vectordb/Cargo.toml, rust/vectordb/src/table.rs
Plumb thru object store construction hook from [lance/pull/1014](https://github.com/lancedb/lance/pull/1014)
=> allow passing ReadParams to dataset when opening a table

docs/src/search.md, node/src/index.ts
=> Add dot product support

python/lancedb/db.py, python/lancedb/query.py, python/lancedb/remote/__init__.py, python/lancedb/table.py, python/lancedb/util.py, python/tests/test_table.py
when encountering bad input data, we can default to principle of least surprise and raise an exception.
=> Set default to error instead of drop

Cargo.toml
we shouldn't auto-upgrade lance
=> Pin lance version

Cargo.toml, node/package-lock.json, node/src/index.ts, rust/ffi/node/Cargo.toml, rust/ffi/node/src/arrow.rs, rust/ffi/node/src/lib.rs, rust/vectordb/src/database.rs, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs
* upgrade
* fixes for the upgrade
* allow JS users to pass custom AWS credentials
TODO:
add JS code to actually allow passing custom creds, right now only the FFI allows custom creds
=> Upgrade lance to 0.5.5, and plumb thru new features from the upgrade

rust/ffi/node/Cargo.toml, rust/ffi/node/src/lib.rs
tested with `RUST_LOG=info npm test`
=> allow logging in JS

docs/src/python/python.md, python/lancedb/pydantic.py, python/pyproject.toml, python/tests/test_pydantic.py
Provide utility to automatically convert Pydantic model to Arrow Schema
Closes #256
=> [Python] Convert Pydantic Model to Arrow Schema

docs/src/embedding.md, docs/src/examples/transformerjs_embedding_search_nodejs.md
=> [docs] small fixes

docs/src/basic.md, docs/src/javascript/README.md, docs/src/javascript/classes/LocalConnection.md, docs/src/javascript/classes/LocalTable.md, docs/src/javascript/classes/OpenAIEmbeddingFunction.md, docs/src/javascript/classes/Query.md, docs/src/javascript/enums/MetricType.md, docs/src/javascript/enums/WriteMode.md, docs/src/javascript/interfaces/AwsCredentials.md, docs/src/javascript/interfaces/Connection.md, docs/src/javascript/interfaces/ConnectionOptions.md, docs/src/javascript/interfaces/EmbeddingFunction.md, docs/src/javascript/interfaces/IvfPQIndexConfig.md, docs/src/javascript/interfaces/Table.md, docs/src/javascript/modules.md, node/src/index.ts, node/tsconfig.json, python/lancedb/remote/table.py, python/lancedb/table.py
=> docs: show how to delete rows in user guide

python/lancedb/table.py
It prevents to open remote dataset.
=> [Bug] Fix dataset path check in Table::open

python/lancedb/db.py, python/lancedb/util.py
=> feat: pass AWS_ENDPOINT environment variable down

python/lancedb/pydantic.py, python/pyproject.toml, python/tests/test_pydantic.py
Support both Pydantic v1 and v2 (breaking changes)
=> [Python] Support pydantic v1 as well

.github/workflows/npm-publish.yml, ci/build_linux_artifacts.sh, ci/manylinux_node/Dockerfile, ci/manylinux_node/build.sh, ci/manylinux_node/install_openssl.sh, ci/manylinux_node/install_protobuf.sh, ci/manylinux_node/prepare_manylinux_node.sh, node/package-lock.json, node/package.json
=> ci: build node in manylinux docker container

python/lancedb/db.py, python/tests/test_db.py
add `ignore_missing` parameter to `drop_table` method
=> Implement drop table if exists

docs/src/python/pydantic.md, python/lancedb/common.py, python/lancedb/db.py, python/lancedb/pydantic.py, python/lancedb/query.py, python/lancedb/table.py, python/tests/test_pydantic.py, python/tests/test_query.py, python/tests/test_table.py
See the documentation changes for details
=> Improve pydantic integration

python/lancedb/common.py, python/lancedb/context.py, python/lancedb/db.py, python/lancedb/embeddings.py, python/lancedb/query.py, python/lancedb/remote/db.py, python/lancedb/remote/table.py, python/lancedb/schema.py, python/lancedb/table.py, python/lancedb/util.py
reduce installation footprint for size conscious applications
=> make pandas an optional dependency in lancedb as well

docs/mkdocs.yml, docs/src/guides/tables.md, docs/test/md_testing.js, docs/test/md_testing.py
* Rename "Reference" -> "Guides" to create distinction b/w api reference and user facing docs
* Add all the various ways to create, add and delete from table
Related - https://github.com/lancedb/lancedb/pull/391
=> [Docs] add Tables guide

python/lancedb/remote/client.py, python/lancedb/remote/db.py
Also moves `request_id` to header instead of request param
=> implement remote drop table call

Cargo.toml, node/package-lock.json, node/src/index.ts
Previously, we are failing to open table when caller uses custom creds, this PR fixes that.
=> Upgrade lance and pass AWS creds when opening a table

docs/mkdocs.yml, docs/src/guides/tables.md, docs/src/integrations/prompttools.md, python/lancedb/db.py
Depends on - https://github.com/lancedb/lancedb/pull/430
=> [DOCS] Update integrations + small typos 

node/src/index.ts
Previously when logging the `LocalConnection` and `LocalTable` classes, we would expose the aws creds inside them. This PR changes the stored creds to a anonymous function to hide the creds
=> use a lambda function to hide the value of credentials when printing a connection/table

python/lancedb/table.py, python/tests/test_table.py
Previously if you needed to add a column to a table you'd have to rewrite the whole table. Instead,
we use the merge functionality from Lance format
to incrementally add columns from another table
or dataframe.
=> [python] Support schema evolution in local LanceDB

node/package-lock.json
This reverts commit ab97e5d63261de597d3af012fd076fb9e18038ce.
=> Revert "Updating package-lock.json"

rust/vectordb/Cargo.toml, rust/vectordb/README.md
A few small changes to make the Rust crate more discoverable.
=> chore: make crate more discoverable

docs/src/python/python.md, python/lancedb/__init__.py, python/lancedb/embeddings/__init__.py, python/lancedb/embeddings/functions.py, python/lancedb/table.py
#467 broken the docs build but that's only run once merged into main. This fixes the errors (verified locally)
=> Fix up docs

Cargo.toml, rust/vectordb/Cargo.toml, rust/vectordb/src/arrow.rs, rust/vectordb/src/data.rs, rust/vectordb/src/data/inspect.rs, rust/vectordb/src/data/sanitize.rs, rust/vectordb/src/error.rs
Split the rust core from #466 for easy review and less merge conflicts.
=> [Rust] schema coerce and vector column inference

python/lancedb/table.py, python/tests/test_db.py
Should fix - https://github.com/lancedb/lancedb/issues/482
=> [Python]Fix record_batch_generator

python/lancedb/util.py
=> fix: increase S3 timeouts

rust/vectordb/src/database.rs
in #486 `connect` started converting path into uri. However, the PR didn't handle relative path and appended `file://` to relative path.
This PR changes the parsing strat to be more rational. If a path is provided instead of url, we do not try anythinng special.
engine and engine params may only be specified when a url with schema is provided
=> refactor connection string processing

.github/workflows/python.yml, docs/src/guides/tables.md, docs/src/python/python.md, python/lancedb/pydantic.py
Enable doctest for pydantic 1.x
and improve docs for embedding functions
closes #497
=> feat: improve pydantic 1.x compat

python/lancedb/remote/__init__.py, python/lancedb/remote/client.py, python/tests/test_remote_client.py
Thanks to #508, I used `attr` instead of the correct package `attrs`
s/attr/attrs
=> fix `import attr` to use `import attrs`

Cargo.toml, python/pyproject.toml, rust/ffi/node/src/index/vector.rs, rust/vectordb/src/table.rs
Bump to lance 0.8.1 for both javascript and python sdk
=> chore: upgrade lance to 0.8.1 

docs/mkdocs.yml, docs/src/cli_config.md, python/lancedb/cli/cli.py, python/pyproject.toml
Usage:
`lancedb`
`lancedb --help`
`lancedb diagnostics --enabled` , `lancedb disgnostics --disabled`
`lancedb config`
=> Basic click CLI setup

Cargo.toml, README.md, docs/src/ann_indexes.md, docs/test/requirements.txt, python/lancedb/remote/table.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_table.py, rust/vectordb/src/io/object_store.rs
Bump lance to 0.8.3 to include GPU training
=> feat: use GPU for index creation.

docs/mkdocs.yml, docs/src/guides/tables.md
A little verbose, but better than being non-discoverable
=> [Docs] Improve visibility of table ops 

Cargo.toml, node/src/index.ts, node/src/test/test.ts, python/lancedb/table.py, python/tests/test_table.py, rust/ffi/node/Cargo.toml, rust/ffi/node/src/index/vector.rs, rust/ffi/node/src/lib.rs, rust/ffi/node/src/table.rs, rust/vectordb/Cargo.toml, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/table.rs
=> feat: cleanup and compaction

docs/README.md, docs/src/index.md, docs/src/search.md
Fix broken link to embedding functions
testing: broken link was verified after local docs build to have been repaired
=> doc: fix broken link and add README

rust/vectordb/src/table.rs
=> feat: expose optimize index api

rust/ffi/node/src/table.rs, rust/vectordb/src/table.rs
expose index remap options in `compact_files`
=> expose remap index api

python/lancedb/db.py, python/tests/test_db.py, rust/vectordb/src/database.rs
https://github.com/lancedb/lance/issues/1385
=> fix!: sort table names

.github/workflows/node.yml, .github/workflows/python.yml, .github/workflows/rust.yml
similar to what we did here:
https://github.com/lancedb/lance/pull/1497
=> ci: cancel in progress runs on new push

.github/workflows/python.yml, .github/workflows/rust.yml
=> chore: apple silicon runner

rust/vectordb/src/io/object_store.rs
mirrored store is not garueeteed to have all the files. Ignore the ones that doesn't exist.
=> skip missing file on mirrored dir when deleting

Cargo.toml, rust/vectordb/src/table.rs
=> upgrade lance to 0.8.14

python/lancedb/remote/client.py, python/lancedb/remote/db.py, python/lancedb/remote/table.py
- added check whether a table exists in SaaS open_table
- remove prefilter not supported warning in SaaS search
- fixed issues for SaaS table_names
=> fix saas open_table and table_names issues

node/src/remote/client.ts
=> fix: node send db header for GET requests

docs/mkdocs.yml, docs/src/robots.txt
Sitemap improves SEO by ranking pages and tracking updates.
=> [Docs][SEO] Add sitemap and robots.txt

python/lancedb/remote/table.py, python/lancedb/table.py, python/tests/test_db.py, python/tests/test_table.py
This is to enable https://github.com/lancedb/lancedb/issues/641.
Should be merged after https://github.com/lancedb/lance/pull/1587 is released.
=> feat(python): expose index cache size

Cargo.toml, node/src/test/test.ts, python/pyproject.toml, rust/ffi/node/Cargo.toml, rust/ffi/node/src/index/vector.rs, rust/vectordb/Cargo.toml, rust/vectordb/src/index/vector.rs, rust/vectordb/src/table.rs
Readying for the next Lance release.
=> chore: upgrade lance to v0.8.17

docs/mkdocs.yml, docs/src/examples/image_embeddings_roboflow.md
In this PR, I add a guide that lets you use Roboflow Inference to calculate CLIP embeddings for use in LanceDB. This post was reviewed by @AyushExel.
=> (docs):Add CLIP image embedding example

rust/vectordb/src/query.rs
expose prefilter flag in vectordb rust code.
=> chore: expose prefilter in lancedb rust

node/src/query.ts, node/src/remote/client.ts, node/src/remote/index.ts, node/src/test/test.ts, rust/ffi/node/src/query.rs
enable prefiltering in node js, both native and remote
=> feat: enable prefilter in node js

node/src/remote/index.ts
was passing this at the wrong position
=> fix: fix passing prefilter flag to remote client

node/package-lock.json
=> chore: update package lock

docs/mkdocs.yml, docs/src/python/saas-python.md, python/lancedb/__init__.py, python/lancedb/remote/db.py, python/lancedb/remote/table.py
=> saas python sdk doc

python/lancedb/table.py, python/lancedb/util.py, python/pyproject.toml, python/tests/test_table.py
Closes #69
Will not pass until https://github.com/lancedb/lance/pull/1585 is released
=> feat(python): add update query support for Python

python/lancedb/fts.py, python/tests/test_fts.py
https://github.com/lancedb/lance/issues/1739
Support nested field reference in full text search
=> feat(python): support nested reference for fts

node/src/index.ts, node/src/remote/index.ts, node/src/test/test.ts, node/tsconfig.json, python/lancedb/remote/table.py, python/lancedb/table.py, python/tests/test_table.py, rust/ffi/node/src/index.rs, rust/ffi/node/src/index/scalar.rs, rust/ffi/node/src/lib.rs, rust/vectordb/src/table.rs
This is a pretty direct binding to the underlying lance capability
=> feat: add the ability to create scalar indices

docs/src/guides/tables.md, docs/src/sql.md, python/lancedb/table.py
=> docs: enhance Update user guide

docs/src/javascript/README.md, docs/src/javascript/classes/DefaultWriteOptions.md, docs/src/javascript/classes/LocalConnection.md, docs/src/javascript/classes/LocalTable.md, docs/src/javascript/classes/OpenAIEmbeddingFunction.md, docs/src/javascript/classes/Query.md, docs/src/javascript/enums/MetricType.md, docs/src/javascript/enums/WriteMode.md, docs/src/javascript/interfaces/AwsCredentials.md, docs/src/javascript/interfaces/CleanupStats.md, docs/src/javascript/interfaces/CompactionMetrics.md, docs/src/javascript/interfaces/CompactionOptions.md, docs/src/javascript/interfaces/Connection.md, docs/src/javascript/interfaces/ConnectionOptions.md, docs/src/javascript/interfaces/CreateTableOptions.md, docs/src/javascript/interfaces/EmbeddingFunction.md, docs/src/javascript/interfaces/IndexStats.md, docs/src/javascript/interfaces/IvfPQIndexConfig.md, docs/src/javascript/interfaces/Table.md, docs/src/javascript/interfaces/UpdateArgs.md, docs/src/javascript/interfaces/UpdateSqlArgs.md, docs/src/javascript/interfaces/VectorIndex.md, docs/src/javascript/interfaces/WriteOptions.md, docs/src/javascript/modules.md, node/README.md
This command hasn't been run for a while...
=> docs: update node API reference

python/lancedb/query.py, python/lancedb/remote/table.py
issue separate requests under the hood and concatenate results
=> feat(python): first cut batch queries for remote api

docs/src/embeddings/embedding_functions.md
In addition to #777, this pull request fixes more typos in the documentation for "Ingest Embedding Functions".
=> Minor corrections for docs of embedding_functions

docs/src/embeddings/embedding_functions.md
Addressed minor typos and grammatical issues to improve readability
=> Minor Fixes to Ingest Embedding Functions Docs

docs/src/notebooks/code_qa_bot.ipynb, docs/src/notebooks/youtube_transcript_search.ipynb
These examples don't work because of changes in openai api from version 1+
=> Make examples work with current version of Openai api's

python/lancedb/query.py
raise exception if fts index does not exist
=> raise exception if fts index does not exist

rust/ffi/node/src/arrow.rs
should fix the error on top of main
https://github.com/lancedb/lancedb/actions/runs/7457190471/job/20288985725
=> fix(rust): not sure why clippy is suddenly unhappy

python/lancedb/table.py, python/tests/test_table.py
=> feat(python): add count_rows with filter option

python/lancedb/remote/client.py, python/lancedb/remote/db.py, python/lancedb/remote/table.py, python/pyproject.toml, python/tests/test_remote_db.py
instead of starting and stopping the current thread's event loop on every http call, just make an http call.
=> use requests instead of aiohttp for underlying http client

.github/workflows/python.yml, python/README.md, python/pyproject.toml
We use `ruff` in CI and dev workflow now.
=> chore: remove black as dependency

docs/src/embeddings/default_embedding_functions.md, python/lancedb/embeddings/__init__.py, python/lancedb/embeddings/gemini_text.py, python/tests/test_embeddings_slow.py
Named it Gemini-text for now. Not sure how complicated it will be to support both text and multimodal embeddings under the same class "gemini"..But its not something to worry about for now I guess.
=> feat(python): Add gemini text embedding function

python/lancedb/query.py, python/lancedb/table.py, python/lancedb/util.py, python/pyproject.toml, python/tests/test_table.py
We should now be able to directly ingest polars dataframes and return results as polars dataframes
=> feat(python): basic polars integration

.github/workflows/python.yml, python/lancedb/cli/cli.py, python/lancedb/conftest.py, python/lancedb/context.py, python/lancedb/embeddings/__init__.py, python/lancedb/embeddings/gemini_text.py, python/lancedb/embeddings/instructor.py, python/lancedb/embeddings/open_clip.py, python/lancedb/embeddings/registry.py, python/lancedb/embeddings/sentence_transformers.py, python/lancedb/embeddings/utils.py, python/lancedb/fts.py, python/lancedb/pydantic.py, python/lancedb/query.py, python/lancedb/remote/client.py, python/lancedb/remote/db.py, python/lancedb/remote/table.py, python/lancedb/table.py, python/lancedb/util.py, python/lancedb/utils/config.py, python/lancedb/utils/events.py, python/lancedb/utils/general.py, python/lancedb/utils/sentry_log.py, python/tests/test_cli.py, python/tests/test_db.py, python/tests/test_embeddings.py, python/tests/test_pydantic.py, python/tests/test_telemetry.py
@eddyxu added instructions for linting here:
https://github.com/lancedb/lancedb/blob/7af213801a091cd5afb0f0814e184fc0b852de47/python/README.md?plain=1#L45-L50
However, we had a lot of failures and weren't checking this in CI. This PR fixes all lints and adds a check to CI to keep us in compliance with the lints.
=> ci: lint and enforce linting

python/lancedb/remote/client.py, python/lancedb/remote/connection_timeout.py, python/lancedb/table.py, python/tests/test_table.py
Add test to ingest fp16 to a database
=> bug: add a test for fp16

node/package-lock.json, node/src/arrow.ts, node/src/index.ts, node/src/test/arrow.test.ts, node/tsconfig.json
Support to make Apache Arrow Table from an array of javascript Records, with optionally provided Schema.
=> feat(js): add helper function to create Arrow Table with schema

nodejs/Cargo.toml, nodejs/__test__/table.test.ts, nodejs/src/index.rs, nodejs/src/iterator.rs, nodejs/src/lib.rs, nodejs/src/query.rs, nodejs/vectordb/native.d.ts, nodejs/vectordb/native.js, nodejs/vectordb/query.ts, nodejs/vectordb/table.ts, rust/vectordb/src/ipc.rs, rust/vectordb/src/query.rs, rust/vectordb/src/utils.rs
* Query as a fluent API and `AsyncIterator<RecordBatch>`
* Much more docs
* Add tests for auto infer vector search columns with different dimensions.
=> feat(napi): Issue queries as node SDK

node/src/test/test.ts, rust/ffi/node/src/arrow.rs, rust/ffi/node/src/index/scalar.rs, rust/ffi/node/src/table.rs, rust/vectordb/src/index.rs, rust/vectordb/src/table.rs
Consolidate various optimize() into one method, similar to postgres VACCUM in the process of preparing Rust API for public use
=> chore(rust): simplified version of optimize

python/lancedb/remote/client.py
Context -  https://etoai.slack.com/archives/C05NC5YSW5V/p1706371205883149
=> chore(python): Temporarily extend remote connection timeout 

docs/mkdocs.yml, docs/src/extra_js/init_ask_ai_widget.js
=> doc: Add documentation chatbot for LanceDB

docs/src/guides/storage.md
Adding some more quick advice for how to setup AWS S3 with LanceDB.
=> docs: provide AWS S3 cleanup and permissions advice

node/package-lock.json, node/package.json
- fix the repo link on npm
- add links for homepage and bug report
=> fix the repo link on npm, add links for homepage and bug report

docs/src/guides/tables.md, docs/src/python/pydantic.md, python/lancedb/table.py
=> make it explicit about the vector column data type

docs/src/hybrid_search.md
1. fixed typos
2. added create_fts_index
=> fix hybrid search example

.cargo/config.toml, Cargo.toml, nodejs/Cargo.toml, nodejs/jest.config.js, rust/ffi/node/Cargo.toml, rust/ffi/node/src/arrow.rs, rust/ffi/node/src/convert.rs, rust/ffi/node/src/error.rs, rust/ffi/node/src/index/scalar.rs, rust/ffi/node/src/index/vector.rs, rust/ffi/node/src/query.rs, rust/ffi/node/src/table.rs, rust/vectordb/Cargo.toml, rust/vectordb/src/connection.rs, rust/vectordb/src/index.rs, rust/vectordb/src/index/vector.rs, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs
* Closes #895 
* Fix cargo clippy
=> chore: add global cargo config to enable minimal cpu target

python/lancedb/embeddings/openai.py, python/tests/test_embeddings_slow.py
=> feat(python): add support new openai embedding functions

.github/workflows/docs_test.yml, docs/src/hybrid_search.md, python/lancedb/query.py, python/lancedb/rerankers/__init__.py, python/lancedb/rerankers/base.py, python/lancedb/rerankers/cohere.py, python/lancedb/rerankers/colbert.py, python/lancedb/rerankers/cross_encoder.py, python/lancedb/rerankers/linear_combination.py, python/lancedb/rerankers/openai.py, python/lancedb/table.py, python/tests/test_rerankers.py
- Most users might not know how to use `QueryBuilder` object. Instead we should just pass the string query. 
- Add new rerankers: Colbert, openai
=> feat(python): Reranker DX improvements

docs/src/faq.md
Based on discussion over discord, adding minor updates to the FAQ section about benchmarks, practical data size and concurrency in LanceDB
=> Minor updates to FAQ

python/lancedb/remote/db.py, python/lancedb/remote/table.py
1. improved error msg for SaaS create_table and create_index
=> added error msg to SaaS APIs

Cargo.toml, node/src/index.ts, node/src/remote/index.ts, node/src/test/test.ts, python/lancedb/merge.py, python/lancedb/remote/table.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_table.py, rust/ffi/node/src/table.rs, rust/vectordb/src/table.rs, rust/vectordb/src/table/merge.rs
=> feat: add support for filter during merge insert when matched

nodejs/Cargo.toml, rust/ffi/node/Cargo.toml
Fixes #956
Same changes as https://github.com/lancedb/lance/pull/1934
=> fix(node): statically link lzma

docs/mkdocs.yml, docs/src/embeddings/api.md, docs/src/embeddings/default_embedding_functions.md, docs/src/hybrid_search/hybrid_search.md, docs/src/notebooks/hybrid_search.ipynb, docs/test/md_testing.py, python/lancedb/embeddings/base.py, python/lancedb/embeddings/bedrock.py, python/lancedb/embeddings/cohere.py, python/lancedb/embeddings/gemini_text.py, python/lancedb/embeddings/gte.py, python/lancedb/embeddings/instructor.py, python/lancedb/embeddings/open_clip.py, python/lancedb/embeddings/openai.py, python/lancedb/embeddings/sentence_transformers.py, python/lancedb/rerankers/cohere.py, python/lancedb/rerankers/colbert.py, python/lancedb/rerankers/cross_encoder.py, python/lancedb/rerankers/openai.py, python/lancedb/util.py
- Rename safe_import -> attempt_import_or_raise (closes https://github.com/lancedb/lancedb/pull/923)
- Update docs
- Add Notebook example (@changhiskhan you can use it for the talk. Comes with "open in colab" button)
- Latency benchmark & results comparison, sanity check on real-world data
- Updates the default openai model to gpt-4
=> feat(python): hybrid search updates, examples, & latency benchmarks

node/src/arrow.ts, node/src/embedding/embedding_function.ts, node/src/index.ts, node/src/test/arrow.test.ts, node/src/test/test.ts, node/tsconfig.json
This PR also reworks the table creation utilities significantly so that they are more consistent, built on top of each other, and thoroughly documented.
=> feat: make it easier to create empty tables

docs/src/notebooks/DisappearingEmbeddingFunction.ipynb
Hey, 
I tried the DisappearingEmbeddingFunction notebook and found some problems that I fixed locally and would love to merge, to improve the experience for others as well.
I also thought about loading the dataset from the Hugging Face Hub, rather than require the user to download it, that would keep the user more in the flow of the notebook IMO. Feel free to let me know what you guys think.
=> apply fixes for notebook

Cargo.toml, node/src/test/test.ts, nodejs/src/table.rs, python/pyproject.toml, python/python/lancedb/query.py, python/python/lancedb/table.py, python/python/tests/test_query.py, rust/ffi/node/src/table.rs, rust/lancedb/src/query.rs
upgrade to lance 0.10.1 and update doc string to reflect dynamic projection options
=> chore: upgrade to lance 0.10.1

node/src/index.ts, node/src/test/test.ts
=> fix: handle uri in object

python/python/lancedb/remote/table.py
the integration test will be covered in another PR: https://github.com/lancedb/sophon/pull/1876
=> add index_stats python api

python/python/lancedb/utils/events.py
Increasing event reporting interval from 5mins to 60mins
=> chore(python): Increase event interval for telemetry

docs/src/guides/tables.md
@wjones127 after fixing https://github.com/lancedb/lancedb/issues/1112 I noticed something else on the docs. There's an odd chunk of the docs missing [here](https://lancedb.github.io/lancedb/guides/tables/#from-a-polars-dataframe). I can see the heading, but after clicking it the contents don't show. 
Apon inspection it was a markdown issue, one tab too many on a whole segment.
This PR fixes it. It looks like this now and the sections appear again:
=> Unhide Pydantic guides in Docs

python/python/lancedb/query.py, python/python/lancedb/rerankers/base.py, python/python/lancedb/rerankers/cohere.py, python/python/lancedb/rerankers/colbert.py, python/python/lancedb/rerankers/cross_encoder.py, python/python/lancedb/rerankers/openai.py, python/python/tests/test_rerankers.py
solves https://github.com/lancedb/lancedb/issues/1086
Usage Reranking with FTS:
```
retriever = db.create_table("fine-tuning", schema=Schema, mode="overwrite")
pylist = [{"text": "Carson City is the capital city of the American state of Nevada. At the  2010 United States Census, Carson City had a population of 55,274."},
{"text": "The Commonwealth of the Northern Mariana Islands is a group of islands in the Pacific Ocean that are a political division controlled by the United States. Its capital is Saipan."},
{"text": "Charlotte Amalie is the capital and largest city of the United States Virgin Islands. It has about 20,000 people. The city is on the island of Saint Thomas."},
{"text": "Washington, D.C. (also known as simply Washington or D.C., and officially as the District of Columbia) is …
```
=> feat(python): Support reranking for vector and fts

nodejs/__test__/table.test.ts
changed the error msg for query with wrong vector dim thus need this change to pass the nodejs tests.
=> fix nodejs test

docs/src/extra_js/init_ask_ai_widget.js
This links out to the new [asklancedb.com](https://asklancedb.com) page.
Screenshots of the change:
=> Adds a Ask LanceDB button to docs.

.github/workflows/npm-publish.yml
=> ci: fix name collision in npm artifacts for vectordb

README.md
=> Update LanceDB Logo in README

node/src/remote/client.ts
=> fix error decoding in nodejs client

Cargo.toml, python/pyproject.toml
Bump lance version to `0.10.7`
=> chore: bump lance version

.github/workflows/build_linux_wheel/action.yml, .github/workflows/pypi-publish.yml, .github/workflows/rust.yml, python/Cargo.toml, rust/lancedb/Cargo.toml
Same deal as https://github.com/lancedb/lance/pull/2098
=> feat: ship fp16kernels in Python wheels

docs/src/notebooks/youtube_transcript_search.ipynb
Fixes issue https://github.com/lancedb/lancedb/issues/1268
=> fix: Docs for embed_func fixed in youtube transcript search notebook

python/python/lancedb/query.py, python/python/lancedb/table.py
=> fix: clearer error that FTS is not supported on object stores

Cargo.toml, rust/lancedb/src/lib.rs
https://github.com/lancedb/lance/releases/tag/v0.10.18
=> chore: bump lance to v0.10.18

node/src/arrow.ts, nodejs/lancedb/arrow.ts
i accidentally left a console.log when doing https://github.com/lancedb/lancedb/pull/1290
=> fix: remove accidental console.log

.github/workflows/python.yml, .github/workflows/rust.yml, Cargo.toml, nodejs/src/table.rs, python/pyproject.toml, python/src/table.rs, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/embeddings.rs, rust/lancedb/src/table.rs
upgrade lance and make fixes for the upgrade
=> feat: upgrade lance to 0.11.0

java/core/lancedb-jni/src/error.rs, java/core/lancedb-jni/src/ffi.rs
this was causing unrelated PR's to fail. https://github.com/lancedb/lancedb/actions/runs/9274579178/job/25517248069?pr=1308
=> chore: clippy warnings inside java bindings

python/python/lancedb/embeddings/base.py, python/python/lancedb/embeddings/bedrock.py, python/python/lancedb/embeddings/cohere.py
Fixes #1329
Will update docs on https://github.com/lancedb/lancedb/pull/1326
=> feat: add support for new cohere models in cohere and bedrock embedding functions

nodejs/__test__/embedding.test.ts, nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/query.ts, nodejs/lancedb/table.ts
closes https://github.com/lancedb/lancedb/issues/1292
closes https://github.com/lancedb/lancedb/issues/1293
=> fix(nodejs): better support for f16 and f64

nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/embedding/registry.ts, nodejs/lancedb/query.ts, nodejs/lancedb/table.ts
closes https://github.com/lancedb/lancedb/issues/1256
=> feat(nodejs): table.search functionality

rust/lancedb/src/table/dataset.rs
most of the time we don't need to reload. Locking the write lock and performing IO is not an ideal pattern.
This PR tries to make the critical section of `.write()` happen less frequently.
This isn't the most ideal solution. The most ideal solution should not lock until the new dataset has been loaded. But that would require too much refactoring.
=> feat: add fast path to dataset reload

rust/lancedb/src/table/dataset.rs
similar to https://github.com/lancedb/lancedb/pull/1354
do locked IO less frequently
=> feat: fast path for checkout_latest

nodejs/__test__/table.test.ts, nodejs/lancedb/merge.ts, nodejs/lancedb/table.ts, nodejs/package-lock.json, nodejs/src/lib.rs, nodejs/src/merge.rs, nodejs/src/table.rs, rust/lancedb/src/table/merge.rs
closes https://github.com/lancedb/lancedb/issues/1349
=> feat(nodejs): merge insert

python/python/lancedb/table.py
- refer #1264
- fixed minor documentation issue
=> docs: remove code-block:: python from docs

node/package.json
i have no idea why this fixes the build.
=> fix(node): node build

.pre-commit-config.yaml, docs/src/guides/storage.md, nodejs/__test__/s3_integration.test.ts, nodejs/biome.json, nodejs/lancedb/remote/client.ts, nodejs/package-lock.json, nodejs/package.json, python/python/lancedb/db.py, python/python/lancedb/table.py, python/python/lancedb/util.py, python/python/tests/test_s3.py, rust/lancedb/Cargo.toml, rust/lancedb/tests/object_store_test.rs
This allows users to specify URIs like:
```
s3+ddb://my_bucket/path?ddbTableName=myCommitTable
```
and it will support concurrent writes in S3.
Closes #534
=> feat: dynamodb commit store support

.github/workflows/docs_test.yml, node/package.json
Fixed nodejs doctest failures due to compiling JNI node.
=> ci: fix nodejs doc test

docs/openapi.yml
Added 3 APIs doc publicly:
- `merge_insert`
- `create_index`
- `create_scalar_index`
=> docs: add merge insert, create index and create scalar index to public rest api doc

docs/src/embeddings/index.md, docs/src/reranking/jina.md, python/python/lancedb/embeddings/__init__.py, python/python/lancedb/embeddings/jinaai.py, python/python/lancedb/rerankers/__init__.py, python/python/lancedb/rerankers/jinaai.py
Integration of Jina Embeddings and Rerankers through its API
=> feat: add Jina integration in Python for Embedding and Reranker

python/python/lancedb/rerankers/linear_combination.py
change typehint on `_invert_score` from `List[float]` to `float`. remove unnecessary typing import
=> refactor: update type hint and remove unused import

docs/mkdocs.yml, docs/src/embeddings/default_embedding_functions.md, docs/src/reranking/index.md, python/python/lancedb/embeddings/jinaai.py
PR to add JinaReranker documentation page to the rerankers index
=> docs: add jina reranker to index

.github/workflows/python.yml, docs/src/python/saas-python.md, python/python/lancedb/pydantic.py, python/python/lancedb/remote/table.py
`merge_insert` API is not shown up on [`RemoteTable`](https://lancedb.github.io/lancedb/python/saas-python/#lancedb.remote.table.RemoteTable)  today
* Also bump `ruff` version as well
=> docs: expose merge_insert doc for remote python SDK

nodejs/__test__/table.test.ts, nodejs/lancedb/query.ts, nodejs/src/query.rs, python/python/lancedb/query.py, python/python/tests/test_query.py, python/src/query.rs
=> fix: handle camelCase column names in select

python/python/lancedb/rerankers/__init__.py, python/python/lancedb/rerankers/rrf.py, python/python/tests/test_rerankers.py
Implements https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf
Refactors the hybrid search only rerrankers test to avoid repetition.
=> feat: add reciprocal rank fusion reranker

nodejs/.npmignore
This PR is for issue - https://github.com/lancedb/lancedb/issues/1358
=> fix: remove source .ts code from published npm package

docs/mkdocs.yml, docs/src/notebooks/lancedb_reranking.ipynb, docs/src/reranking/rrf.md
- RRF reranker
- Jina Reranker results
=> docs: add rrf docs and update reranking notebook with Jina reranker results

Cargo.toml, python/Cargo.toml, python/pyproject.toml, python/python/lancedb/query.py, python/python/lancedb/remote/table.py, python/src/arrow.rs, python/src/connection.rs, python/src/query.rs, python/src/table.rs, rust/lancedb/Cargo.toml, rust/lancedb/src/io/object_store.rs
Changelog: https://github.com/lancedb/lance/releases/tag/v0.15.0
* Fixes #1466
* Closes #1475
* Fixes #1446
=> feat: upgrade lance to 0.15.0

.github/workflows/java.yml
This PR is for issue - https://github.com/lancedb/lancedb/issues/1331
=> fix: run java stages in parallel

nodejs/__test__/registry.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/embedding/index.ts, nodejs/lancedb/embedding/openai.ts, nodejs/lancedb/sanitize.ts
Fixes [#1496](https://github.com/lancedb/lancedb/issues/1496)
=> fix(nodejs): address import issues in `lancedb` npm module

docs/src/embeddings/default_embedding_functions.md, python/pyproject.toml, python/python/lancedb/embeddings/__init__.py, python/python/lancedb/embeddings/watsonx.py, python/python/tests/test_embeddings_slow.py
Related issue: https://github.com/lancedb/lancedb/issues/1412
=> feat(python): add watsonx embeddings to registry

python/python/lancedb/remote/table.py
Sohpon test - https://github.com/lancedb/sophon/pull/2269
=> feat(python): support embedding functions in remote table

python/python/lancedb/_lancedb.pyi, python/python/tests/test_index.py, python/src/index.rs
=> feat(python): index config repr method

python/python/lancedb/_lancedb.pyi, python/python/tests/test_table.py, python/src/table.rs
=> feat(python): optimize stats repr method

nodejs/lancedb/index.ts, python/src/table.rs
=> fix(node): export optimize options

python/python/lancedb/query.py, python/python/tests/test_query.py
=> feat(python): add to_list to async api

nodejs/__test__/table.test.ts, nodejs/lancedb/indices.ts, nodejs/lancedb/query.ts, nodejs/src/index.rs
=> feat(nodejs): add bitmap and label list index types in nodejs

nodejs/__test__/table.test.ts, nodejs/lancedb/table.ts, nodejs/src/table.rs
=> feat(nodejs): add delete unverified

python/python/lancedb/table.py
=> docs: add `create_fts_index` doc in Python API Reference

python/python/lancedb/table.py, python/python/tests/test_table.py, python/src/table.rs
=> feat(python): add delete unverified parameter

python/python/lancedb/query.py
=> fix: rerank attribute unknown

docs/src/examples/serverless_lancedb_with_s3_and_lambda.md
I believe this import is outdated.
=> docs: update serverless_lancedb_with_s3_and_lambda.md

python/python/lancedb/query.py, python/python/tests/test_query.py, python/python/tests/test_table.py
=> fix(bug): limit fix

node/src/test/test.ts, rust/ffi/node/src/lib.rs
=> fix(node): read consistency level fix

python/python/lancedb/db.py, python/python/lancedb/query.py, python/python/lancedb/remote/arrow.py, python/python/lancedb/remote/db.py, python/python/lancedb/table.py, python/python/tests/test_db.py
resolve #1562
- fix that RemoteTable can't create table from iterator
- infer the schema from the iterator
- refactor the checks for creating table
=> feat: support to create table from record batch iterator

Cargo.toml, python/pyproject.toml, rust/ffi/node/src/table.rs, rust/lancedb/src/table.rs
Changelog: https://github.com/lancedb/lance/releases/tag/v0.17.0
Highlights:
* You can do "phrase queries" by adding double quotes around phrases (multiple tokens) in FTS.
Added follow ups in: https://github.com/lancedb/lancedb/issues/1611
=> feat: upgrade lance to v0.17.0

nodejs/__test__/table.test.ts, nodejs/lancedb/query.ts, nodejs/src/query.rs
=> feat(nodejs): expose offset

python/python/lancedb/dependencies.py, python/python/lancedb/table.py, python/python/tests/test_table.py
fixes #1625 
Support PyArrow.RecordBatch, pa.dataset.Dataset, pa.dataset.Scanner, paRecordBatchReader
=> fix: support pyarrow input types

node/src/index.ts, node/src/remote/client.ts, node/src/test/test.ts
Fixes #1622 
To sync with python API
=> feat(node): let NODE API region default to us-east-1

python/python/lancedb/rerankers/answerdotai.py, python/python/lancedb/rerankers/colbert.py
Fixes https://github.com/lancedb/lancedb/issues/1641
=> fix: allow pass optional args in colbert reranker

python/python/lancedb/table.py, python/python/tests/test_remote_db.py
=> feat: fix creating empty table and creating table by a list of RecordBatch for remote python sdk

rust/lancedb/Cargo.toml, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table/merge.rs
* Implements:
* Add
* Update
* Delete
* Merge-Insert
=> feat(rust): remote client write data endpoint

.bumpversion.toml, .github/workflows/java-publish.yml, .github/workflows/make-release-commit.yml, java/core/lancedb-jni/Cargo.toml, java/core/pom.xml, java/pom.xml, release_process.md
Enable bump java pom.xml versions
Enable auto java release when detect stable github release
=> ci: enable java auto release

python/python/lancedb/remote/table.py, python/python/lancedb/table.py, python/python/lancedb/util.py
-  fixes https://github.com/lancedb/lancedb/issues/1697.
- unifies vector column inference logic for remote and local table to prevent future disparities.
- Updates docstring in RemoteTable to specify empty queries are not supported
=> feat(python): allow explicit hybrid search query pattern in SaaS (feat parity)

rust/lancedb/src/index/vector.rs, rust/lancedb/src/table.rs
=> fix: hnsw default partitions

python/python/lancedb/embeddings/base.py, python/python/tests/test_embeddings.py, python/python/tests/test_embeddings_slow.py
=> fix(EmbeddingFunction): modify safe_model_dump to explicitly exclude class fields with underscore

rust/lancedb/src/connection.rs, rust/lancedb/src/remote/db.rs
Adds rename to remote table. Pre-requisite for https://github.com/lancedb/lancedb/pull/1701
=> feat(rust): remote rename table

.github/workflows/docs_test.yml, .github/workflows/rust.yml
=> ci: change to use github runner

python/python/lancedb/merge.py, python/python/lancedb/table.py, python/python/tests/test_table.py, python/src/table.rs
=> feat(python): merge_insert in async Python

python/python/lancedb/common.py, python/python/lancedb/db.py, python/python/lancedb/table.py, python/python/tests/test_table.py
=> feat(python): drop support for dictionary in Table.add

rust/lancedb/src/remote/table.rs
=> feat(rust): `list_indices` in remote SDK

Cargo.toml, node/src/test/test.ts, python/pyproject.toml
Includes changes from v0.18.1 and v0.18.2:
* [v0.18.1 change log](https://github.com/lancedb/lance/releases/tag/v0.18.1)
* [v0.18.2 change log](https://github.com/lancedb/lance/releases/tag/v0.18.2)
Closes #1656
Closes #1615
Closes #1661
=> feat: upgrade Lance to v0.18.2

rust/lancedb/src/index.rs, rust/lancedb/src/table.rs
=> fix: list_indices can handle fts indexes

rust/lancedb/src/connection.rs
Fixes https://github.com/lancedb/lancedb/issues/1750
=> feat(rust): allow `add_embedding` on `create_empty_table`

python/python/lancedb/query.py
=> fix: explain plan options

nodejs/src/lib.rs
=> fix(node): update default log level to warn

.github/workflows/npm-publish.yml, .github/workflows/rust.yml
https://github.com/lancedb/lancedb/actions/runs/11748512661/job/32732745458
=> fix: arm64 runner proto already installed bug

docs/src/ann_indexes.md, docs/test/requirements.txt
=> docs: search param explanation for OSS doc

.github/workflows/python.yml, python/python/lancedb/embeddings/registry.py, python/python/lancedb/rerankers/voyageai.py, python/python/lancedb/table.py, python/python/tests/test_embeddings.py
* Make Pandas `DataFrame` works with embedding function + Subset of columns
* Make `lancedb.create_table()` work with embedding function
=> fix: use pandas with pydantic embedding column

rust/lancedb/Cargo.toml, rust/lancedb/examples/bedrock.rs, rust/lancedb/src/embeddings.rs, rust/lancedb/src/embeddings/bedrock.rs
Add amazon bedrock embedding function to rust sdk.
1.  Add BedrockEmbeddingModel ( lancedb/src/embeddings/bedrock.rs)
2. Add example lancedb/examples/bedrock.rs
=> feat: add new feature, add amazon bedrock embedding function

.github/workflows/npm-publish.yml
Started to actually fix this, but it was taking too long https://github.com/lancedb/lancedb/pull/1831
=> ci: disable Windows Arm64 until the release builds work

.github/workflows/npm-publish.yml
=> ci: remove invalid references

python/python/tests/test_query.py
Also remove weird `MockTable` fixture.
=> test(python): test `with_row_id` in sync query

.bumpversion.toml, .cargo/config.toml, .github/workflows/npm-publish.yml, ci/manylinux_node/build_lancedb.sh, ci/manylinux_node/build_vectordb.sh, node/package.json, nodejs/npm/linux-arm64-musl/README.md, nodejs/npm/linux-arm64-musl/package.json, nodejs/npm/linux-x64-musl/README.md, nodejs/npm/linux-x64-musl/package.json, nodejs/package.json
untested 4 artifacts at: https://github.com/FuPeiJiang/lancedb/actions/runs/11926579058
node-native-linux-aarch64-musl 22.6 MB
node-native-linux-x86_64-musl 23.6 MB
nodejs-native-linux-aarch64-musl 26.7 MB
nodejs-native-linux-x86_64-musl 27 MB
this follows the same process as: https://github.com/lancedb/lancedb/pull/1816#issuecomment-2484816669
Closes #1388
Closes #1107
=> ci: musl x64,arm64

Cargo.toml, nodejs/lancedb/table.ts, nodejs/src/table.rs, python/pyproject.toml, python/python/lancedb/remote/table.py, python/python/lancedb/table.py, python/src/table.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
Will require update to lance dependency to bring in this change which makes the version serializable https://github.com/lancedb/lance/pull/3143
=> feat: add list_versions to typescript, rust and remote python sdks

python/Cargo.toml, python/pyproject.toml, python/python/lancedb/embeddings/openai.py, python/python/lancedb/pydantic.py, python/python/tests/test_embeddings.py, python/python/tests/test_embeddings_slow.py, python/python/tests/test_pydantic.py
BREAKING-CHANGE: change Pydantic Vector field to be nullable by default.
Closes #1577
=> fix(python)!: handle bad openai embeddings gracefully

docs/src/guides/scalar_index.md, docs/src/sql.md
improved the docs on build a scalar index and pre-/post-filtering
=> docs: improve scalar index and filtering

rust/lancedb/src/connection.rs, rust/lancedb/src/query.rs, rust/lancedb/src/remote/table.rs
https://github.com/lancedb/lancedb/issues/1804
=> fix: default limit for remote nodejs client

Cargo.toml, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs
* Support subset of storage options as remote options
* Send Azure storage account name via HTTP header
=> feat: support remote options for remote lancedb connection

docs/src/embeddings/available_embedding_models/text_embedding_functions/openai_embedding.md, python/python/lancedb/embeddings/openai.py
=> feat(python): add support for Azure OpenAPI SDK

Cargo.toml, python/Cargo.toml, python/pyproject.toml, python/src/arrow.rs, python/src/connection.rs, python/src/error.rs, python/src/index.rs, python/src/lib.rs, python/src/query.rs, python/src/table.rs
Upstream change log: https://github.com/lancedb/lance/releases/tag/v0.20.0
=> feat: upgrade to Lance v0.20.0

rust/lancedb/src/remote/table.rs, rust/lancedb/src/utils.rs
=> chore: simplify arrow json conversion

.github/workflows/npm-publish.yml
* Clean up old commented out jobs
* Fix runner issue that caused these failures: https://github.com/lancedb/lancedb/actions/runs/12186754094
=> ci: fix nodejs release jobs

rust/lancedb/src/utils.rs
=> fix: data type parsing

node/package-lock.json, node/package.json, nodejs/package-lock.json, nodejs/package.json
* Set `private: false` so we can publish new binary packages
* Add missing windows binary reference
=> ci: fix release

python/python/lancedb/remote/table.py, python/python/tests/test_remote_db.py
=> fix: create_scalar_index in cloud

nodejs/__test__/arrow.test.ts, nodejs/__test__/registry.test.ts, nodejs/__test__/table.test.ts, nodejs/package-lock.json, nodejs/package.json
=> fix(nodejs): upgrade arrow versions

python/python/tests/test_remote_db.py, rust/lancedb/src/remote/table.rs
Closes https://github.com/lancedb/lancedb/issues/1876
=> feat: support offset in remote client

nodejs/__test__/table.test.ts, nodejs/lancedb/indices.ts, nodejs/src/index.rs
=> feat(node): support FTS options in nodejs

docs/mkdocs.yml, docs/src/python/saas-python.md, python/python/lancedb/remote/table.py, python/python/lancedb/table.py
* Add `See Also` section to `cleanup_old_files` and `compact_files` so they know it's linked to `optimize`.
* Fixes link to `compact_files` arguments
* Improves formatting of note.
=> docs: improve optimization docs

docs/src/python/python.md, python/python/lancedb/index.py
=> docs: add new indexes to python docs

python/python/lancedb/query.py, python/python/tests/test_query.py
Fixes https://github.com/lancedb/lancedb/issues/1952
Added `to_polars` method to `AsyncQueryBase`.
=> feat(python): add `to_polars` to `AsyncQueryBase`

CONTRIBUTING.md, docs/README.md, nodejs/CONTRIBUTING.md, nodejs/README.md, python/CONTRIBUTING.md, python/Makefile, python/README.md
* Adds basic contributing guides.
* Simplifies Python development with a Makefile.
=> docs: contributing guide

docs/src/search.md, nodejs/__test__/table.test.ts, nodejs/examples/search.test.ts, nodejs/lancedb/query.ts, nodejs/package-lock.json, nodejs/package.json, nodejs/src/query.rs, python/python/lancedb/query.py, python/python/tests/docs/test_distance_range.py
=> feat: support distance range in queries

.github/workflows/npm-publish.yml, ci/sysroot-aarch64-pc-windows-msvc.sh
successful runs: https://github.com/FuPeiJiang/lancedb/actions/runs/12698662005
=> ci: add `dbghelp.lib` to sysroot-aarch64-pc-windows-msvc.sh (#1975)

python/python/lancedb/embeddings/voyageai.py
This PR fixes the broken Embedding API for Voyageai.
=> fix: broken voyageai embedding API

nodejs/__test__/table.test.ts
Addresses failure on `main`: https://github.com/lancedb/lancedb/actions/runs/12757756657/job/35558683317
=> chore: fix test of error message

Cargo.toml, python/pyproject.toml
Now the version actually exists :)
=> feat: upgrade lance 0.22.1b1

docs/src/js/README.md, docs/src/js/_media/CONTRIBUTING.md, docs/src/js/classes/Table.md, docs/src/js/classes/VectorQuery.md, docs/src/js/globals.md, docs/src/js/interfaces/IvfPqOptions.md, docs/src/js/namespaces/rerankers/README.md, docs/src/js/namespaces/rerankers/classes/RRFReranker.md, docs/src/js/namespaces/rerankers/interfaces/Reranker.md, nodejs/__test__/table.test.ts, nodejs/lancedb/table.ts, nodejs/src/table.rs, python/python/lancedb/table.py, python/python/tests/test_index.py, python/python/tests/test_table.py, python/src/table.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
=> feat: add `drop_index()` method

docs/src/search.md, python/python/lancedb/query.py, python/python/tests/docs/test_multivector.py, python/python/tests/test_query.py
this also enable async API to query with 2d numpy array
=> docs: claim LanceDB supports float16/float32/float64 for multivector

Cargo.toml, python/pyproject.toml
Fixes https://github.com/lancedb/lancedb/issues/2043
=> feat: upgrade lance to v0.23.0-beta.2

.github/workflows/build_linux_wheel/action.yml, .github/workflows/pypi-publish.yml
Based on changes made in Lance:
* https://github.com/lancedb/lance/pull/3409
* https://github.com/lancedb/lance/pull/3411
=> ci(python): stop using deprecated 2_24 manylinux for arm

docs/src/notebooks/tables_guide.ipynb
Fix example for section ## From pandas DataFrame
=> docs: pandas example

docs/src/guides/tables.md, docs/src/guides/tables/merge_insert.md, docs/test/md_testing.py, nodejs/examples/ann_indexes.test.ts, nodejs/examples/basic.test.ts, nodejs/examples/biome.json, nodejs/examples/custom_embedding_function.test.ts, nodejs/examples/merge_insert.test.ts, nodejs/examples/sentence-transformers.test.ts, nodejs/examples/util.ts, python/python/lancedb/table.py, python/python/tests/docs/test_guide_tables.py, python/python/tests/docs/test_merge_insert.py
=> docs: user guide for merge insert

docs/src/basic.md, docs/src/search.md, python/python/tests/docs/test_basic.py
=> docs: add sync/async tabs to quickstart

Cargo.lock, Cargo.toml, rust/lancedb/Cargo.toml, rust/lancedb/src/table/datafusion.rs
This also adds a basic unit test for the table provider
=> fix: ensure metadata erased from schema call in table provider

Cargo.lock, python/python/lancedb/arrow.py, python/python/lancedb/embeddings/base.py, python/python/lancedb/table.py, python/python/tests/test_embeddings.py, python/python/tests/test_util.py
Makes our preprocessing pipeline do transforms in streaming fashion, so users can do larger-then-memory writes.
Closes #2082
=> feat(python): streaming larger-than-memory writes

Cargo.lock, Cargo.toml, python/pyproject.toml, rust/lancedb/src/remote/db.rs
Upstream changelog: https://github.com/lancedb/lance/releases/tag/v0.23.0
=> feat: upgrade Lance to 0.23.0

docs/src/js/functions/makeArrowTable.md, nodejs/__test__/arrow.test.ts, nodejs/__test__/table.test.ts, nodejs/examples/full_text_search.test.ts, nodejs/lancedb/arrow.ts
=> feat(node): support inserting and upserting subschemas

docs/src/ann_indexes.ts, docs/src/basic_legacy.ts, docs/src/search_legacy.ts, docs/src/sql_legacy.ts
Minor cleanup to help debug future CI failures
=> docs: standardize node example prints

python/Makefile, python/python/tests/test_embeddings.py, python/python/tests/test_remote_db.py
=> chore: improve dev instructions for Python

Cargo.lock, Cargo.toml
this also upgrades object_store to 0.11.0, snafu to 0.8
=> feat: upgrade lance to 0.23.1-beta.4

python/python/lancedb/pydantic.py, python/python/tests/test_pydantic.py
=> fix: support optional nested pydantic model

Cargo.lock, Cargo.toml
this is fixed in lance so upgrade lance to 0.23.2-beta1
=> fix: flat FTS panic with prefilter and update lance

Cargo.lock, Cargo.toml, python/pyproject.toml
this fixes a bug in SQ, see https://github.com/lancedb/lance/pull/3476 for more details
=> chore: upgrade lance to v0.23.3-beta.1

Cargo.lock, Cargo.toml
This reverts commit 2f0c5baea22ff340b9d8a9590e2c5025a93405ca.
=> feat: reapply upgrade lance to v0.23.3-beta.1

python/pyproject.toml, python/python/lancedb/_lancedb.pyi, python/python/lancedb/table.py
=> feat(python): drop hard dependency on pylance

docs/mkdocs.yml, docs/src/extra_js/reo.js
This PR adds reo integration to the lancedb documentation website.
=> chore: add reo integration

Cargo.lock, docs/openapi.yml, docs/src/ann_indexes.md, docs/src/concepts/index_hnsw.md, docs/src/concepts/index_ivfpq.md, docs/src/embeddings/understanding_embeddings.md, docs/src/integrations/langchain.md, docs/src/integrations/llamaIndex.md, docs/src/javascript/enums/MetricType.md, docs/src/javascript/interfaces/IvfPQIndexConfig.md, docs/src/js/interfaces/HnswPqOptions.md, docs/src/js/interfaces/HnswSqOptions.md, docs/src/js/interfaces/IvfPqOptions.md, docs/src/search.md, node/src/index.ts, nodejs/lancedb/indices.ts, python/python/lancedb/index.py, python/python/lancedb/query.py, python/python/lancedb/remote/table.py, python/python/lancedb/table.py, python/python/tests/test_query.py, python/python/tests/test_table.py, rust/lancedb/examples/ivf_pq.rs, rust/lancedb/src/lib.rs
=> fix: metric type inconsistency

nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts
=> fix(nodejs): workaround for apache-arrow null vector issue

docs/src/js/classes/Index.md, docs/src/js/functions/packBits.md, docs/src/js/globals.md, docs/src/js/interfaces/IvfFlatOptions.md, docs/src/search.md, nodejs/__test__/table.test.ts, nodejs/examples/search.test.ts, nodejs/lancedb/index.ts, nodejs/lancedb/indices.ts, nodejs/lancedb/util.ts, nodejs/src/index.rs
=> feat: support binary vector and IVF_FLAT in TypeScript

.github/workflows/npm-publish.yml
Should fix failure seen here: https://github.com/lancedb/lancedb/actions/runs/13999958170/job/39207039825
=> ci(node): setup URL so auth token is picked up

docs/src/troubleshooting.md, python/python/lancedb/__init__.py
=> feat(python): warn on fork

README.md
=> docs: add banner for LanceDB Cloud in public beta

python/python/lancedb/query.py
Removes reference of nonexistent method.
=> fix: update Query pydoc

python/pyproject.toml, python/python/lancedb/embeddings/voyageai.py, python/python/tests/test_embeddings_slow.py
=> fix(python): voyageai regression multimodal supercedes text models

Cargo.lock
=> chore: cargo update on main

Cargo.lock, Cargo.toml, node/package-lock.json
This is preparation for a stable release
=> feat: update lance to 0.31.1

Cargo.lock, Cargo.toml
Changelog: https://github.com/lancedb/lance/releases/tag/v0.32.0
Fixes #2521
=> feat: upgrade Lance to v0.32.0

.github/workflows/docs.yml, .gitignore, CLAUDE.md, ci/update_lockfiles.sh
I promise this time I tested it locally :)
=> ci: remove more mentions of node

Cargo.lock, Cargo.toml
detials: https://github.com/lancedb/lance/releases/tag/untagged-5191abd48c1fbe76f746
=> chore: upgrade lance to 0.33.0-beta.4

python/python/lancedb/table.py, python/python/tests/test_query.py, python/python/tests/test_torch.py
This allows a lancedb Table to act as a torch dataset.
=> feat: add __getitems__ method impl for torch integration

python/python/lancedb/query.py
Fix doctest in query.py to include cumulative_cpu, now that lance includes that.
=> fix!: fix doctest in query.py

rust/lancedb/src/table/datafusion.rs
Some of the data fusion optimizers optimize based on data statistics (e.g. total bytes, number of rows).
If those statistics are not supplied, optimizers cannot optimize on top.
One example is Anti Hash Join which can optimize from LeftAnti (Left: big table, Right: small table) to RightAnti (Left: small table, Right: big table). Left Anti requires reading the whole big & small table while RightAnti only requires reading the whole left table and supports limit push down to only read partial of big table
=> fix: add partition statistics to MetadataEraser

Cargo.lock, Cargo.toml, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/database.rs, rust/lancedb/src/database/namespace.rs, rust/lancedb/src/lib.rs
This PR adds support for namespace-backed databases through lance-namespace integration, enabling centralized table management through namespace APIs.
=> feat(rust): support namespace backed database

Cargo.lock, Cargo.toml, rust/lancedb/src/data/inspect.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/table.rs, rust/lancedb/src/table/datafusion.rs, rust/lancedb/src/table/dataset.rs, rust/lancedb/src/utils.rs
https://github.com/lancedb/lance/releases/tag/v0.38.0
=> feat: upgrade lance to 0.38.0
