lancedb/lancedb

python/lancedb/embeddings.py
prints a warning if the python version > 3.10
```
>>> data = with_embeddings(embed_func, df, show_progress=True)
WARNING: rate limit only support up to 3.10, proceeding without rate limiter
```
Tested with Python 3.11.2 (macos) and  Python 3.10.6 (linux)
Long term we should look into another rate limiter library, possibly https://pypi.org/project/throttler/
=> skipping embeddings rate limit when python version > 3.10

.github/workflows/python.yml, docs/src/fts.md, python/lancedb/fts.py, python/lancedb/query.py, python/pyproject.toml, python/tests/test_embeddings.py, python/tests/test_fts.py, python/tests/test_query.py, python/tests/test_table.py
pypi does not allow packages to be uploaded that has a direct reference
for now we'll just ask the user to install tantivy separately
=> move tantivy-py installation to be separate from wheel

docs/mkdocs.yml, docs/src/ann_indexes.md, docs/src/search.md
=> [Doc] Metrics types.

python/lancedb/db.py, python/lancedb/query.py, python/lancedb/remote/__init__.py, python/lancedb/remote/client.py, python/lancedb/remote/errors.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_e2e_remote_db.py, python/tests/test_query.py, python/tests/test_remote_client.py, python/tests/test_remote_db.py, python/tests/test_table.py
* to_df() is now async, added `to_df_blocking` to convenience
* add remote lancedb client to public lancedb
* make lancedb connection class understand url scheme `lancedb+<connection_type>://<host>:<port>`.
=> port remote connection client into lancedb

docs/mkdocs.yml
Currently, the default mkdocs material favicon is used for docs in prod. I'm not sure if we have some other asset intended for this use, but meanwhile reusing the logo as a favicon would be better than nothing.
=> Add favicon in docs

Cargo.lock, rust/ffi/node/Cargo.toml, rust/vectordb/Cargo.toml, rust/vectordb/src/database.rs, rust/vectordb/src/table.rs
* bump to 0.5.2 to pick up S3 auth fixes
* make `dataset_read_params` a public attribute
* add `open_table_with_params` on `Database`
=> bump lance to 0.5.2, make object store construction hook public

node/src/index.ts, node/src/test/test.ts, python/lancedb/db.py, rust/ffi/node/src/lib.rs, rust/vectordb/src/database.rs, rust/vectordb/src/table.rs
Support `createTable(name, data, mode?)`  to be consistent with Python.
Closes #242
=> [Node] Create Table with WriteMode

docs/src/javascript/README.md, docs/src/javascript/classes/LocalConnection.md, docs/src/javascript/classes/LocalTable.md, docs/src/javascript/classes/OpenAIEmbeddingFunction.md, docs/src/javascript/classes/Query.md, docs/src/javascript/enums/MetricType.md, docs/src/javascript/enums/WriteMode.md, docs/src/javascript/interfaces/Connection.md, docs/src/javascript/interfaces/EmbeddingFunction.md, docs/src/javascript/interfaces/Table.md, docs/src/javascript/modules.md, node/.eslintrc.js, node/README.md, node/src/index.ts
Solves #244 :
Problem was function overloading in the interface caused some weird `typedoc` formatting, so breaking it apart into methods fixed the issue.
Also regenerated and updated javascript docs
=> [docs] fixed javascript docs for overloaded functions

.gitignore, .pre-commit-config.yaml, python/lancedb/db.py, python/lancedb/table.py, python/tests/test_query.py, python/tests/test_remote_client.py, python/tests/test_table.py
Sometimes LangChain would insert a single `[np.nan]` as a placeholder if the embedding function failed. This causes a problem for Lance format because then the array can't be stored as a FixedSizedListArray.
Instead:
1. By default we remove rows with embedding lengths less than the maximum length in the batch
2. If `strict=True` kwargs is set to True, then a `ValueError` is raised if the embeddings aren't all the same length
=> Handle NaN input data

rust/ffi/node/src/lib.rs, rust/vectordb/src/lib.rs, rust/vectordb/src/table.rs
`Table::add(.., mode: WriteMode)`, which is a public API, currently uses the WriteMode exported from `lance`. Re-export it to lancedb so that the pub API looks better.
=> [Rust] Re-export WriteMode from lancedb instead of lance

python/lancedb/db.py, python/lancedb/pydantic.py, python/lancedb/query.py, python/tests/test_db.py, python/tests/test_query.py
1. Create empty table was failing because top level API wasn't exposed correctly.
2. Passing in different vector column was failing because QueryBuilder.to_arrow didn't pass the vector_column argument
3. Remove deprecated abstractstaticmethod usage in pydantic
=> [python] Fix a few minor bugs

node/package-lock.json, python/pyproject.toml, rust/ffi/node/src/lib.rs, rust/vectordb/src/database.rs, rust/vectordb/src/index/vector.rs, rust/vectordb/src/table.rs
* `Table::open()` from absolute path, and gives the responsibility of organizing metadata out of Table object
* Fix Clippy warnings
* Add `Table::checkout(version)` API
=> [Rust] Checkout a version of dataset.

python/lancedb/remote/table.py, python/lancedb/table.py, python/tests/test_table.py
`Table::count()` will be linearly slower with more fragments ingested.
=> [Python] Do not return Table count for every add operation

python/lancedb/table.py, python/tests/test_db.py
Makes the following work so all the formats accepted by `create_table()` are also accepted by `add()`
```
import lancedb
import pyarrow as pa
db = lancedb.connect("/tmp")
def make_batches():
for i in range(5):
yield pa.RecordBatch.from_arrays(
[
pa.array([[3.1, 4.1], [5.9, 26.5]]),
pa.array(["foo", "bar"]),
pa.array([10.0, 20.0]),
],
["vector", "item", "price"],
)
schema = pa.schema([
pa.field("vector", pa.list_(pa.float32())),
pa.field("item", pa.utf8()),
pa.field("price", pa.float32()),
])
tbl = db.create_table("table4", make_batches(), schema=schema)
tbl.add(make_batches())
```
=> [python] Allow adding via iterators

docs/src/basic.md, python/lancedb/db.py, python/lancedb/table.py, python/tests/test_db.py
Saves users from having to explicitly call `LanceModel.to_arrow_schema()` when creating an empty table.
See new docs for full details.
=> Automatically convert pydantic model

python/lancedb/table.py
Both existing implementations, `LanceTable` and `RemoteTable`, of the `Table` abstract class implements `schema` as a property. This PR aligns the interface and implementation.
=> [breaking change] make schema a property

python/lancedb/db.py, python/tests/test_db.py
#416 Fixed.
added drop_database() method . This deletes all the tables from the database with a single command.
=> implementation of drop_database

Cargo.toml, docs/src/ann_indexes.md, docs/src/examples/transformerjs_embedding_search_nodejs.md, docs/src/python/arrow.md, node/src/test/test.ts, python/lancedb/query.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_fts.py, python/tests/test_query.py
BREAKING CHANGE: The `score` column has been renamed to `_distance` to more accurately describe the semantics (smaller means closer / better).
=> chore: upgrade Lance and rename score to _distance

python/lancedb/table.py, python/tests/test_table.py
This adds LanceTable.restore as a temporary feature. It reads data from a previous version and creates
a new snapshot version using that data. This makes the version writeable unlike checkout. This should be replaced once the feature is implemented in pylance.
=> [python] Temporary restore feature

python/lancedb/table.py, python/tests/test_db.py
It improves the UX as iterators can be of any type supported by the table (plus recordbatch) & there is no separate requirement. 
Also expands the test cases for pydantic & arrow schema.
If this is looks good I'll update the docs.
Example usage:
```
class Content(LanceModel):
vector: vector(2)
item: str
price: float
def make_batches():
for _ in range(5):
yield from [ 
pd.DataFrame({
"vector": [[3.1, 4.1], [1, 1]],
"item": ["foo", "bar"],
"price": [10.0, 20.0],
}),
[
{"vector": [3.1, 4.1], "item": "foo", "price": 10.0},
{"vector": [5.9, 26.5], "item": "bar", "price": 20.0},
],
pa.RecordBatch.from_arrays(
[
pa.array([[3.1, 4.1], [5.9, 26.5]], pa.list_(pa.float32(), 2)),
pa.array(["foo", "bar"]),
pa.array([10.0, 20.0]),
], 
["vector", "item", "price"],
),
[
Content(vector=[3.1, 4.1], …
```
=> Make creating (and adding to) tables via Iterators more flexible & intuitive

.bumpversion.cfg, node/package.json, rust/ffi/node/Cargo.toml, rust/vectordb/Cargo.toml
This reverts commit 87e9a0250f80dc9672d71837bc9c17b228933f16.
I triggered the nodejs release commit GHA by mistake. Reverting it.
The tag will be removed manually.
=> Revert "Bump version: 0.2.4 → 0.2.5"

python/lancedb/table.py, python/tests/test_table.py
Combine delete and append to make a temporary update feature that is only enabled for the local python lancedb.
The reason why this is temporary is because it first has to load the data that matches the where clause into memory, which is technical unbounded.
=> [python] Temporary update feature

docs/src/guides/tables.md, docs/src/notebooks/tables_guide.ipynb, docs/src/python/pydantic.md, python/lancedb/pydantic.py, python/tests/test_db.py, python/tests/test_pydantic.py, python/tests/test_query.py, python/tests/test_table.py
Rename `lance.pydantic.vector` to `Vector` and deprecate `vector(dim)`
=> [Python] Pydantic vector field with default value

.github/workflows/node.yml, Cargo.toml, docker-compose.yml, node/package-lock.json, node/package.json, node/src/integration_test/test.ts, rust/vectordb/Cargo.toml, rust/vectordb/src/database.rs
This PR exposes dynamodb based commit to `vectordb` and JS SDK (will do python in another PR since it's on a different release track)
This PR also added aws integration test using `localstack`
This PR adds uri parameters to DB connection string. User may specify `engine` in the connection string to let LanceDB know that the user wants to use an external store when reading and writing a table. User may also pass any parameters required by the commitStore in the connection string, these parameters will be propagated to lance.
e.g.
```
vectordb.connect("s3://my-db-bucket?engine=ddb&ddbTableName=my-commit-table")
```
will automatically convert table path to
```
s3+ddb://my-db-bucket/my_table.lance?&ddbTableName=my-commit-table
```
=> progagate uri query string to lance; add aws integration tests

.github/workflows/python.yml, docs/src/guides/tables.md, docs/src/python/python.md, python/lancedb/conftest.py, python/lancedb/embeddings/functions.py, python/lancedb/pydantic.py, python/tests/test_db.py, python/tests/test_embeddings_slow.py, python/tests/test_table.py, rust/vectordb/src/database.rs
python/python.md contains typos in the class references
=> ci: fix docs build

python/lancedb/__init__.py
This is read from importlib package version which comes from pyproject.toml. This is so that we don't need to specify the version in multiple places and bumpversion works well.
Closes #468
=> feat: add lancedb.__version__

Cargo.toml, node/src/test/test.ts
This PR upgrade lance to `0.7.5`, which include fixes for searching an empty dataset.
This PR also adds two tests in node SDK to make sure searching empty dataset do no throw
=> fix: upgrade lance to 0.7.5 and add tests for searching empty dataset

python/pyproject.toml
The `attr` project is unrelated to `attrs` that also provides the `attr` namespace (see also <https://hynek.me/articles/import-attrs/>).
It used to _usually_ work, because attrs is a dependency of aiohttp and somehow took precedence over `attr`'s `attr`.
Yes, sorry, it's a mess.
=> [Python] Fix attrs dependency

python/pyproject.toml
Closes #513
For each of these, I found the minimum version that would allow the unit tests to pass.
=> fix: define minimum dependency versions

python/lancedb/embeddings/functions.py, python/lancedb/query.py, python/lancedb/remote/table.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_query.py
We have experimental support for prefiltering (without ANN) in pylance. This means that we can now apply a filter BEFORE vector search is performed. This can be done via the `.where(filter_string, prefilter=True)` kwargs of the query.
Limitations:
- When connecting to LanceDB cloud, `prefilter=True` will raise NotImplemented
- When an ANN index is present, `prefilter=True` will raise NotImplemented
- This option is not available for full text search query
- This option is not available for empty search query (just filter/project)
Additional changes in this PR:
- Bump pylance version to v0.8.0 which supports the experimental prefiltering.
=> feat(python): expose prefilter to lancedb

docs/src/ann_indexes.md, docs/src/basic.md, docs/src/fts.md, docs/src/search.md
I only modified those docs pages that are untouched in existing unmerged PRs, so hopefully there are no merge conflicts!
1. The `tantivy-py` version specified in the docs doesn't work (pip install fails), but with the latest version of pip and wheel installed on my Mac, I was able to just `pip install tantivy` and FTS works great for me. I updated the docs page to include this in 7ca4b757ce2d56a17c0f1fa53df2bafcf5e45dc5 but can always modify to another specific version in case this breaks any tests.
2. The `.add()` method for Python should take in a list of dicts as the first option (to also align with the JS API), and additionally, users can pass an existing pandas DataFrame to add to a table. Hope this makes sense.
3. I've had multiple conversations with users who are unclear that the …
=> [DOCS][PYTHON]  Update docs for clarity

Cargo.toml, node/src/integration_test/test.ts, rust/ffi/node/src/lib.rs, rust/vectordb/Cargo.toml, rust/vectordb/src/database.rs, rust/vectordb/src/io.rs, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/lib.rs, rust/vectordb/src/table.rs, rust/vectordb/src/utils.rs
This PR implements a mirroring object store and allows and table to be mirrored to a local path when param `mirroredStore` is set in the url
=> implement mirroring object store

rust/vectordb/src/io/object_store.rs
closes #541 
two functions was calling itself instead of routing to primary
=> fix stackoverflow

README.md
If you run the README javascript example in typescript, it complains that the type of limit is a function and cannot be set to a number.
=> Use query.limit(..) in README

README.md, docs/src/ann_indexes.md, docs/src/basic.md, docs/src/embedding.md, docs/src/examples/serverless_lancedb_with_s3_and_lambda.md, docs/src/fts.md, docs/src/index.md, docs/src/notebooks/multimodal_search.ipynb, docs/src/notebooks/youtube_transcript_search.ipynb, docs/src/python/arrow.md, docs/src/search.md, python/README.md, python/lancedb/__init__.py, python/lancedb/context.py, python/lancedb/query.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_context.py, python/tests/test_db.py, python/tests/test_e2e_remote_db.py, python/tests/test_fts.py, python/tests/test_io.py, python/tests/test_query.py, python/tests/test_remote_client.py, python/tests/test_remote_db.py, python/tests/test_table.py
Add `to_list` to return query results as list of python dict (so we're not too pandas-centric). Closes #555 
Add `to_pandas` API and add deprecation warning on `to_df`. Closes #545
=> feat: add to_list and to_pandas api's

docs/mkdocs.yml
Proposal to resolve #563.
This globally sets `show_source: true` (per file setting is also possible, [see here](https://mkdocstrings.github.io/usage/).
Example of how docs would look:
Expanded:
=> docs: show source of documented functions

node/src/arrow.ts, node/src/remote/client.ts, node/src/remote/index.ts
Add more APIs to remote table for Node SDK
* `add` rows
* `overwrite` table with rows
* `create` table
This has been tested against dev stack
=> implement remote api calls for table mutation

Cargo.toml, python/pyproject.toml
=> chore: bump lance version in python/rust lancedb

node/src/integration_test/test.ts, rust/vectordb/src/io/object_store.rs
we now only exclude `_latest.manifest` from replication
=> feat: include manifest files in mirrow store

rust/vectordb/src/table.rs
Prior to this PR, to get a new version of a table, we need to re-open the table. This has a few downsides w.r.t. performance:
* Object store is recreated, which takes time and throws away existing warm connections
* Commit handler is thrown aways as well, which also may contain warm connections
=> feat: add checkout method to table to reuse existing store and connections

python/lancedb/pydantic.py, python/tests/test_embeddings_slow.py
Closes #594
The embedding functions are pydantic models so multiple instances with the same parameters are considered ==, which means that if you have multiple embedding columns it's possible for the embeddings to get overwritten. Instead we use `is` instead of == to avoid this problem.
testing: modified unit test to include this case
=> fix(python): fix multiple embedding functions bug

python/lancedb/table.py, python/tests/test_db.py
Support for prefiltering with an index was added in lance version 0.8.7.  We can remove the lancedb check that prevents this. Closes #261
=> feat: allow prefiltering with index

python/lancedb/query.py
Added the prefilter flag argument to the `LanceQueryBuilder.where`.
This should make it display here:
https://lancedb.github.io/lancedb/python/python/#lancedb.query.LanceQueryBuilder.select
And also in intellisense like this:
Also adds some improved documentation about the `where` argument to this method.
=> added api docs for prefilter flag

docs/mkdocs.yml, python/lancedb/utils/sentry_log.py
- posthog charges per event and docs events are registered very frequently. We can keep tracking them on GA
- Reduced sentry trace factor
=> Disable posthog on docs & reduce sentry trace factor

python/lancedb/conftest.py, python/lancedb/embeddings/base.py, python/lancedb/embeddings/cohere.py, python/lancedb/embeddings/utils.py, python/lancedb/query.py, python/lancedb/table.py, python/tests/test_embeddings.py
Users ingesting data using rate limited apis don't need to manually make the process sleep for counter rate limits
resolves #579
=> Exponential standoff retry support for handling rate limited embedding functions

node/src/remote/client.ts, node/src/test/test.ts
https://github.com/lancedb/lancedb/issues/623
Fixes issue trying to print response status when using remote client. If the error is not an HTTP error (e.g. dns/network failure), there won't be a response.
=> fix: node remote connection handles non http errors

python/lancedb/remote/table.py
Please note: this is not tested as we don't have a server here and testing against a mock object wouldn't be that interesting.
=> feat: add RemoteTable.version in Python

ci/build_macos_artifacts.sh
there's build failure for the rust artifact but the macos arm64 build for npm publish still passed. So we had a silent failure for 2 releases. By setting error to immediate this should cause fail immediately.
=> chore: set error handling to immediate

.github/workflows/npm-publish.yml
We had some build issues with npm publish for cross-compiling arm64 macos on an x86 macos runner. Switching to m1 runner for now until someone has time to deal with the feature flags.
follow-up tracked here: #688
=> chore: Use m1 runner for npm publish

python/lancedb/table.py, python/lancedb/utils/events.py
- Register open_table as event 
- Because we're dropping 'seach' event currently, changed the name to 'search_table' and introduced throttling
- Throttled events will be counted once per time batch so that the user is registered but event count doesn't go up by a lot
=> chore(python): Reduce posthog event count

node/src/index.ts, node/src/query.ts, node/src/test/test.ts, rust/ffi/node/src/query.rs, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs
Note this currently the filter/where is only implemented for LocalTable so that it requires an explicit cast to "enable" (see new unit test). The alternative is to add it to the Table interface, but since it's not available on RemoteTable this may cause some user experience issues.
=> feat: LocalTable for vectordb now supports filters without vector search

.github/workflows/npm-publish.yml
Most recent release failed because `release` depends on `node-macos`, but we renamed `node-macos` to `node-macos-{x86,arm64}`. This fixes that by consolidating them back to a single `node-macos` job, which also has the side effect of making the file shorter.
=> ci: fix broken npm publication

.github/workflows/python.yml, python/lancedb/pydantic.py, python/lancedb/table.py, python/tests/test_table.py
Closes #562
Previous we were converting pydantic model to dict as `dict(x)`, which doesn't touch nested models. Instead, we now use BaseModel.[model_dump](https://docs.pydantic.dev/2.5/concepts/serialization/#dictmodel-and-iteration) (2.x) or BaseModel.[dict()](https://docs.pydantic.dev/1.10/usage/exporting_models/) (1.x).
=> feat: support nested pydantic schema

rust/vectordb/src/io/object_store.rs, rust/vectordb/src/query.rs
Allow user to select any column for vector query in rust
=> feat: allow custom column name in query

python/lancedb/remote/__init__.py
pass vector column name to remote as well.
`vector_column` is already part of `Query` just declearing it as part to `remote.VectorQuery` as well
=> feat: pass vector column name to remote backend

docs/requirements.txt, docs/src/search.md, python/lancedb/query.py, python/tests/test_table.py
Closes https://github.com/lancedb/lance/issues/1738
We add a `flatten` parameter to the signature of `to_pandas`. By default this is None and does nothing.
If set to True or -1, then LanceDB will flatten structs before converting to a pandas dataframe. All nested structs are also flattened. If set to any positive integer, then LanceDB will flatten structs up to the specified level of nesting.
=> feat(python): add option to flatten output in to_pandas

Cargo.toml, python/pyproject.toml, python/tests/test_table.py, rust/vectordb/src/io/object_store.rs
This brings in some important bugfixes related to take and aarch64 Linux. See changes at: https://github.com/lancedb/lance/releases/tag/v0.9.1
=> upgrade lance to v0.9.1

python/lancedb/table.py, python/tests/test_fts.py
This forces the user to replace the whole FTS directory when re-creating the index, prevent duplicate data from being created. Previously, the whole dataset was re-added to the existing index, duplicating existing rows in the index.
This (in combination with lancedb/lance#1707) caused #726, since the duplicate data emitted duplicate indices for `take()` and an upstream issue caused those queries to fail.
This solution isn't ideal, since it makes the FTS index temporarily unavailable while the index is built. In the future, we should have multiple FTS index directories, which would allow atomic commits of new indexes (as well as multiple indexes for different columns).
Fixes #498.
Fixes #726.
=> fix: prevent duplicate data in FTS index

.github/ISSUE_TEMPLATE/bug-node.yml, .github/ISSUE_TEMPLATE/bug-python.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature.yml
This PR adds issue templates, which help two recurring issues:
* Users forget to tell us whether they are using the Node or Python SDK
* Issues don't get appropriate tags
This doesn't force the use of the templates. Because we set `blank_issues_enabled: true`, users can still create a custom issue.
=> chore: add issue templates

docs/src/basic.md, docs/src/guides/tables.md, docs/src/sql.md
=> doc(javascript): minor improvement on docs for working with tables

python/lancedb/pydantic.py, python/tests/test_pydantic.py
For object detection, each row may correspond to an image and each image can have multiple bounding boxes of x-y coordinates. This means that a `bbox` field is potentially "list of list of float". This adds support in our pydantic-pyarrow conversion for nested lists.
=> feat(python): support list of list fields from pydantic schema

docs/src/fts.md, python/lancedb/query.py, python/pyproject.toml, python/tests/test_fts.py
Closes #721 
fts will return results as a pyarrow table. Pyarrow tables has a `filter` method but it does not take sql filter strings (only pyarrow compute expressions). Instead, we do one of two things to support  `tbl.search("keywords").where("foo=5").limit(10).to_arrow()`:
Default path: If duckdb is available then use duckdb to execute the sql filter string on the pyarrow table.
Backup path: Otherwise, write the pyarrow table to a lance dataset and then do `to_table(filter=<filter>)`
Neither is ideal. 
Default path has two issues:
1. requires installing an extra library (duckdb)
2. duckdb mangles some fields (like fixed size list => list)
Backup path incurs a latency penalty (~20ms on ssd) to write the resultset to disk.
In the short term, once #676 is addressed, we can write the …
=> feat(python): add post filtering for full text search

docs/src/guides/tables.md, python/lancedb/pydantic.py, python/pyproject.toml, python/tests/test_pydantic.py, python/tests/test_table.py
If you add timezone information in the Field annotation for a datetime then that will now be passed to the pyarrow data type.
I'm not sure how pyarrow enforces timezones, right now, it silently coerces to the timezone given in the column regardless of whether the input had the matching timezone or not. This is probably not the right behavior. Though we could just make it so the user has to make the pydantic model do the validation instead of doing that at the pyarrow conversion layer.
=> feat: add timezone handling for datetime in pydantic

python/lancedb/embeddings/openai.py, python/lancedb/embeddings/utils.py, python/pyproject.toml, python/tests/test_embeddings_slow.py
API has changed significantly, namely `openai.Embedding.create` no longer exists. 
https://github.com/openai/openai-python/discussions/742
Update the OpenAI embedding function and put a minimum on the openai sdk version.
=> chore(python): update embedding API to use openai 1.6.1

node/src/arrow.ts, node/src/test/test.ts
Add support for adding lists of string input (e.g., list of categorical labels)
Follow-up items: #757 #758
=> feat(js): support list of string input

docs/src/embeddings/embedding_functions.md
I found that it was quite incoherent to have to read through the documentation and having to search which submodule that each class should be imported from. 
For example, it is cumbersome to have to navigate to another documentation page to find out that `EmbeddingFunctionRegistry` is from `lancedb.embeddings`
=> Add relevant imports for each step

python/lancedb/fts.py, python/tests/test_fts.py
If the input text is None, Tantivy raises an error
complaining it cannot add a NoneType. We handle this
upstream so None's are not added to the document.
If all of the indexed fields are None then we skip
this document.
=> chore(python): handle NaN input in fts ingestion

docs/src/fts.md, python/lancedb/fts.py, python/lancedb/table.py
By default tantivy-py uses 128MB heapsize. We change the default to 1GB and we allow the user to customize this
locally this makes `test_fts.py` run 10x faster
=> feat(python): Set heap size to get faster fts indexing performance

node/src/index.ts, node/src/test/test.ts, rust/ffi/node/src/arrow.rs, rust/ffi/node/src/convert.rs, rust/ffi/node/src/lib.rs, rust/ffi/node/src/query.rs, rust/ffi/node/src/table.rs
Close #773 
we pass an empty table over IPC so we don't need to manually deal with serde. Then we just return the schema attribute from the empty table.
=> feat(node): support table.schema for LocalTable

python/lancedb/pydantic.py, python/tests/test_fts.py, python/tests/test_pydantic.py
closes #792 
There is no generic pydantic->pyarrow parser so we have to make do with our own for the time being. As a result we do need to deal with a lot of different mapping cases.
The old style `Optional[int]` creates a `types.GenericAlias` which we handled whereas `str | None` creates a `types.UnionType` which we didn't handle.
=> feat(python): support new style optional syntax

python/lancedb/query.py, python/tests/test_fts.py
addresses #797 
Problem: tantivy does not expose option to explicitly
Proposed solution here: 
1. Add a `.phrase_query()` option
2. Under the hood, LanceDB takes care of wrapping the input in quotes and replace nested double quotes with single quotes
I've also filed an upstream issue, if they support phrase queries natively then we can get rid of our manual custom processing here.
=> feat(python): add phrase query option for fts

python/lancedb/query.py, python/tests/test_table.py
=> chore(python): add docstring for limit behavior

node/package-lock.json, node/package.json, node/src/arrow.ts, node/src/index.ts, node/src/test/test.ts
Closes #774
Caveat: only handles top level field order.
For nested subfields you still need to manually
ensure the order is correct (for now).
=> feat(node): align incoming data to table schema

python/lancedb/embeddings/gemini_text.py, python/lancedb/embeddings/openai.py, python/lancedb/embeddings/utils.py
This pull request adds check for the presence of an environment variable `OPENAI_API_KEY` and removes an unused parameter in `retry_with_exponential_backoff` function.
=> Add openai api key not found help

python/lancedb/embeddings/gemini_text.py
```
UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types' warnings.warn(message, UserWarning)
```
=> chore(python): get rid of Pydantic deprication warning in embedding fcn

docs/src/guides/tables.md, python/lancedb/db.py, python/lancedb/table.py, python/tests/test_db.py
This mimics CREATE TABLE IF NOT EXISTS behavior.
We add `db.create_table(..., exist_ok=True)` parameter.
By default it is set to False, so trying to create
a table with the same name will raise an exception.
If set to True, then it only opens the table if it
already exists. If you pass in a schema, it will
be checked against the existing table to make sure
you get what you want. If you pass in data, it will
NOT be added to the existing table.
=> feat(python): add exist_ok option to create table

docs/src/basic.md, python/lancedb/table.py, python/tests/test_table.py
#811 allowed us to ingest polars dataframes directly and turn search results into polars dataframes.
This PR supports converting the entire LanceDB table into a lazy polars DataFrame (i.e., it does not read everything into memory immediately).
=> feat(python): allow the entire table to be converted a polars dataframe

python/lancedb/table.py
LazyFrame doesn't allow for iteration in batches so reading it all into memory will likely blow up. So for now we just don't support ingesting LazyFrame directly. if it's small enough, you can explicitly call `collect` and pass in a polars DataFrame
=> chore(python): turn off lazy frame ingestion

python/lancedb/remote/client.py, python/lancedb/remote/connection_timeout.py
Adds an HTTPAdapter to the remote python client that will close idle connections.
This should resolve the issue where our load balancer front-end would decide to close the TCP connection, but the client (using requests module) might send a request before it receives the FIN/ACK packet (resulting in `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`). 
We'll handle this by closing idle connections early on the client side. The default idle time is 300 seconds, but can be overridden by passing env var `LANCE_CLIENT_CONNECTION_TIMEOUT` (expects an int value)
=> fix: remote python client closes idle connections

node/src/index.ts, node/src/remote/index.ts, python/lancedb/__init__.py
Allow passing API key as env var:
```shell
export LANCEDB_API_KEY=sh_123...
```
with this set, apiKey argument can omitted from `connect`
```js
const db = await vectordb.connect({
uri: "db://test-proj-01-ae8343",
region: "us-east-1",
})
```
```py
db = lancedb.connect(
uri="db://test-proj-01-ae8343",
region="us-east-1",
)
```
=> allow passing api key as env var

rust/ffi/node/src/lib.rs, rust/ffi/node/src/table.rs, rust/vectordb/src/connection.rs, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/lib.rs
In NodeJS and Python,  LanceDB establishes a connection to a db. In Rust core, it is called Database. 
We should be consistent with the naming.
=> chore(rust): provide a  Connection trait to match python and nodejs SDK

nodejs/src/query.rs, rust/ffi/node/src/query.rs, rust/vectordb/src/index.rs, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/lib.rs, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs, rust/vectordb/src/utils.rs
* Easy to type
* Handle `String, &str, [String] and [&str]` well without manual conversion
* Fix function name to be verb
* Improve docstring of Rust.
* Promote `query` and `search()` to public `Table` trait
=> feat: improve the rust table query API and documents

rust/vectordb/src/connection.rs, rust/vectordb/src/lib.rs
* Bring the feature parity of Rust connect methods.
* A global connect method that can connect to local and remote / cloud table, as the same as in js/python today.
=> feat(rust): provide connect and connect_with_options in Rust SDK

node/src/index.ts, rust/ffi/node/src/lib.rs, rust/ffi/node/src/table.rs, rust/vectordb/src/connection.rs
Passed the following tests
```ts
const keyId = process.env.AWS_ACCESS_KEY_ID;
const secretKey = process.env.AWS_SECRET_ACCESS_KEY;
const sessionToken = process.env.AWS_SESSION_TOKEN;
const region = process.env.AWS_REGION;
const db = await lancedb.connect({
uri: "s3://bucket/path",
awsCredentials: {
accessKeyId: keyId,
secretKey: secretKey,
sessionToken: sessionToken,
},
awsRegion: region,
} as lancedb.ConnectionOptions);
console.log(await db.createTable("test", [{ vector: [1, 2, 3] }]));
console.log(await db.tableNames());
console.log(await db.dropTable("test"))
```
=> fix(node): pass AWS credentials to db level operations

.github/workflows/docs.yml, .github/workflows/docs_test.yml, .github/workflows/make-release-commit.yml, .github/workflows/pypi-publish.yml, .github/workflows/python-make-release-commit.yml, .github/workflows/python.yml
Github action is deprecating old node-16 runtime.
=> ci: bump to new version of python action to use node 20 gIthub action runtime

docs/src/python/python.md, python/lancedb/merge.py, python/lancedb/remote/table.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_table.py
This adds the python bindings requested in #870 The javascript/rust bindings will be added in a future PR.
=> feat: upgrade to lance 0.9.11 and expose merge_insert

python/lancedb/remote/table.py, python/lancedb/table.py
=> docs: add cleanup_old_versions and compact_files to `Table` for documentation purposes

python/lancedb/remote/client.py, python/lancedb/remote/db.py, python/tests/test_remote_db.py
Adds capability to the remote python SDK to retry requests (fixes #911)
This can be configured through environment:
- `LANCE_CLIENT_MAX_RETRIES`= total number of retries. Set to 0 to disable retries. default = 3
- `LANCE_CLIENT_CONNECT_RETRIES` = number of times to retry request in case of TCP connect failure. default = 3
- `LANCE_CLIENT_READ_RETRIES` = number of times to retry request in case of HTTP request failure. default = 3
- `LANCE_CLIENT_RETRY_STATUSES` = http statuses for which the request will be retried. passed as comma separated list of ints. default `500, 502, 503`
- `LANCE_CLIENT_RETRY_BACKOFF_FACTOR` = controls time between retry requests. see [here](https://github.com/urllib3/urllib3/blob/23f2287eb526d9384dddeedb6f6345e263bb9b86/src/urllib3/util/retry.py#L141-L146). …
=> fix: add request retry to python client

python/README.md, python/lancedb/__init__.py, python/lancedb/db.py, python/lancedb/pydantic.py, python/lancedb/table.py, python/pyproject.toml, python/tests/test_embeddings.py, python/tests/test_table.py
This PR refactors how we handle read consistency: does the `LanceTable` class always pick up modifications to the table made by other instance or processes. Users have three options they can set at the connection level:
1. (Default) `read_consistency_interval=None` means it will not check at all. Users can call `table.checkout_latest()` to manually check for updates.
2. `read_consistency_interval=timedelta(0)` means **always** check for updates, giving strong read consistency.
3. `read_consistency_interval=timedelta(seconds=20)` means check for updates every 20 seconds. This is eventual consistency, a compromise between the two options above.
There is now an explicit difference between a `LanceTable` that tracks the current version and one that is fixed at a historical version. We now …
=> feat(python): add `read_consistency_interval` argument

node/src/index.ts, node/src/test/test.ts, nodejs/src/table.rs, nodejs/vectordb/native.d.ts, nodejs/vectordb/table.ts, python/lancedb/remote/table.py, python/lancedb/table.py, rust/ffi/node/src/table.rs, rust/vectordb/src/index.rs, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/table.rs
A `count_rows` method that takes a filter was recently added to `LanceTable`.  This PR adds it everywhere else except `RemoteTable` (that will come soon).
=> feat: add a filterable count_rows to all the lancedb APIs

docs/mkdocs.yml, docs/src/hybrid_search/hybrid_search.md, docs/src/notebooks/hybrid_search.ipynb
- Fixed typos and added some clarity to the hybrid search docs
- Changed "Airbnb" case to be as per the [official company name](https://en.wikipedia.org/wiki/Airbnb) (the "bnb" shouldn't be capitalized", and the text in the document aligns with this
- Fixed headers in nav bar
=> [docs]: Fix typos and clarity in hybrid search docs

docs/mkdocs.yml, docs/src/hybrid_search/eval.md
These are some minimal evaluation benchmarks. The Reranker docs need another iteration of overhaul which should put the latency and evaluation (hit-rate) metrics in the same page. But this is needed for a talk later today
=> docs: Minimal reranking evaluation benchmarks

.cargo/config.toml
We depend on C static runtime, but not all Windows machines have that. So might be worth statically linking it.
https://github.com/reorproject/reor/issues/36#issuecomment-1948876463
=> fix: use static C runtime on Windows

python/lancedb/__init__.py, python/lancedb/remote/db.py, python/lancedb/remote/table.py, python/tests/test_table.py
Currently if a batch request is given to the remote API, each query is sent sequentially. We should allow the user to specify a threadpool.
=> feat(python): add optional threadpool for batch requests

docs/mkdocs.yml, docs/src/extra_js/meta_tag.js
I think this should work. Need to deploy it to be sure as it can be tested locally. Can be tested here.
2 things about this solution:
* All pages have a same meta tag, i.e, lancedb banner
* If needed, we can automatically use the first image of each page and generate meta tags using the ultralytics mkdocs plugin that we did for this purpose - https://github.com/ultralytics/mkdocs
=> docs: Add meta tag for image preview

nodejs/src/connection.rs, nodejs/src/table.rs, rust/ffi/node/src/lib.rs, rust/ffi/node/src/table.rs, rust/vectordb/examples/simple.rs, rust/vectordb/src/connection.rs, rust/vectordb/src/data/sanitize.rs, rust/vectordb/src/io/object_store.rs, rust/vectordb/src/lib.rs, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs, rust/vectordb/src/utils.rs
This is the start of a more comprehensive refactor and stabilization of the Rust API.  The `Connection` trait is cleaned up to not require `lance` and to match the `Connection` trait in other APIs.  In addition, the concrete implementation `Database` is hidden.
BREAKING CHANGE: The struct `crate::connection::Database` is now gone.  Several examples opened a connection using `Database::connect` or `Database::connect_with_params`.  Users should now use `vectordb::connect`.
BREAKING CHANGE: The `connect`, `create_table`, and `open_table` methods now all return a builder object.  This means that a call like `conn.open_table(..., opt1, opt2)` will now become `conn.open_table(...).opt1(opt1).opt2(opt2).execute()`  In addition, the structure of options has changed slightly.  However, no options …
=> refactor: rust vectordb API stabilization of the Connection trait

docs/src/guides/tables.md, node/src/index.ts, nodejs/__test__/index.test.ts, nodejs/__test__/table.test.ts, nodejs/package-lock.json, nodejs/package.json, nodejs/src/connection.rs, nodejs/src/lib.rs, nodejs/src/table.rs, nodejs/vectordb/index.ts, nodejs/vectordb/native.d.ts, nodejs/vectordb/table.ts, rust/ffi/node/src/lib.rs, rust/ffi/node/src/table.rs, rust/vectordb/src/connection.rs, rust/vectordb/src/index.rs, rust/vectordb/src/query.rs, rust/vectordb/src/table.rs, rust/vectordb/src/table/dataset.rs
This PR adds the same consistency semantics as was added in #828. It *does not* add the same lazy-loading of tables, since that breaks some existing tests.
This closes #998.
=> feat(node): add `read_consistency_interval` to Node and Rust

.github/workflows/python.yml, .github/workflows/remote-integration.yml, .github/workflows/rust.yml, .gitignore, .pre-commit-config.yaml, python/python/lancedb/embeddings/instructor.py, python/python/lancedb/fts.py, python/python/lancedb/remote/table.py, python/python/lancedb/schema.py, python/src/error.rs, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/error.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/remote.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/tests/lancedb_cloud.rs
This will eventually replace the remote table implementations in python and node.
=> feat: Initial remote table implementation for rust

.github/workflows/run_tests/action.yml, nodejs/__test__/connection.test.ts, nodejs/__test__/table.test.ts, nodejs/__test__/tsconfig.json, nodejs/lancedb/connection.ts, nodejs/lancedb/native.d.ts, nodejs/lancedb/table.ts, nodejs/package.json, nodejs/src/connection.rs, nodejs/src/table.rs, python/ASYNC_MIGRATION.md, python/Cargo.toml, python/python/lancedb/_lancedb.pyi, python/python/lancedb/common.py, python/python/lancedb/db.py, python/python/lancedb/table.py, python/python/tests/test_db.py, python/src/connection.rs, python/src/error.rs, python/src/lib.rs, python/src/table.rs, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/error.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/remote/util.rs, rust/lancedb/tests/lancedb_cloud.rs
I've also started `ASYNC_MIGRATION.MD` to keep track of the breaking changes from sync to async python.
=> feat: port create_table to the async python API and the remote rust API

python/python/lancedb/embeddings/openai.py
=> feat(python): add model_names() method to openai embedding function

docs/src/embeddings/default_embedding_functions.md
=> Fix default_embedding_functions.md

docs/src/ann_indexes.md, docs/src/basic.md, docs/src/concepts/index_ivfpq.md, docs/src/faq.md
The renaming of `vectordb` to `lancedb` broke the [quick start docs](https://lancedb.github.io/lancedb/basic/#__tabbed_5_3) (it's pointing to a non-existent directory). This PR fixes the code snippets and the paths in the docs page.
Additionally, more fixes related to indexing docs below 👇🏽.
=> [docs]: Fix issues with Rust code snippets in "quick start"

python/python/lancedb/query.py, python/python/tests/test_fts.py, python/python/tests/test_table.py
1. filtering with fts mutated the schema, which caused schema mistmatch problems with hybrid search as it combines fts and vector search tables.
2. fts with filter failed with `with_row_id`. This was because row_id was calculated before filtering which caused size mismatch on attaching it after. 
3. The fix for 1 meant that now row_id is attached before filtering but passing a filter to `to_lance` on a dataset that already contains `_rowid` raises a panic from lance. So temporarily, in case where fts is used with a filter AND `with_row_id`, we just force user to using the duckdb pathway.
=> fix(python): Few fts patches

.pre-commit-config.yaml, nodejs/__test__/arrow.test.ts, nodejs/__test__/connection.test.ts, nodejs/__test__/table.test.ts, nodejs/eslint.config.js, nodejs/lancedb/connection.ts, nodejs/lancedb/embedding/openai.ts, nodejs/lancedb/indexer.ts, nodejs/lancedb/native.d.ts, nodejs/lancedb/query.ts, nodejs/lancedb/sanitize.ts, nodejs/src/connection.rs, python/python/lancedb/_lancedb.pyi, python/python/lancedb/db.py, python/python/tests/test_db.py, python/src/connection.rs, rust/ffi/node/src/lib.rs, rust/lancedb/examples/simple.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/tests/lancedb_cloud.rs
The synchronous table_names function in python lancedb relies on arrow's filesystem which behaves slightly differently than object_store.  As a result, the function would not work properly in GCS.
However, the async table_names function uses object_store directly and thus is accurate.  In most cases we can fallback to using the async table_names function and so this PR does so.  The one case we cannot is if the user is already in an async context (we can't start a new async event loop).  Soon, we can just redirect those users to use the async API instead of the sync API and so that case will eventually go away.  For now, we fallback to the old behavior.
=> feat: page_token / limit to native table_names function.  Use async table_names function from sync table_names function

rust/lancedb/src/table.rs, rust/lancedb/src/table/dataset.rs
#1002 accidentally changed `checkout_latest` to do nothing if the table was already in latest mode. This PR makes sure it forces a reload of the table (if there is a newer version).
=> fix: make checkout_latest force a reload

python/python/lancedb/embeddings/openai.py
=> fix(python): fix typo in passing in the api_key explicitly

python/python/lancedb/table.py, python/python/tests/test_embeddings.py
The LanceDB embeddings registry allows users to annotate the pydantic model used as table schema with the desired embedding function, e.g.:
```python
class Schema(LanceModel):
id: str
vector: Vector(openai.ndims()) = openai.VectorField()
text: str = openai.SourceField()
```
Tables created like this does not require embeddings to be calculated by the user explicitly, e.g. this works:
```python
table.add([{"id": "foo", "text": "rust all the things"}])
```
However, trying to construct pydantic model instances without vector doesn't because it's a required field.
Instead, you need add a default value:
```python
class Schema(LanceModel):
id: str
vector: Vector(openai.ndims()) = openai.VectorField(default=None)
text: str = openai.SourceField()
```
then this completes without errors:
```python …
```
=> feat(python): support optional vector field in pydantic model

python/pyproject.toml, python/python/lancedb/util.py, python/python/tests/test_io.py
I know there's a larger effort to have the python client based on the core rust implementation, but in the meantime there have been several issues (#1072 and #485) with some of the azure blob storage calls due to pyarrow not natively supporting an azure backend. To this end, I've added an optional import of the fsspec implementation of azure blob storage [`adlfs`](https://pypi.org/project/adlfs/) and passed it to `pyarrow.fs`. I've modified the existing test and manually verified it with some real credentials to make sure it behaves as expected.
It should be now as simple as:
```python
import lancedb
db = lancedb.connect("az://blob_name/path")
table = db.open_table("test")
table.search(...)
```
Thank you for this cool project and we're excited to start using this for real shortly! 🎉  And …
=> fix(python): Add python azure blob read support

docs/src/concepts/index_ivfpq.md
This PR fixes https://github.com/lancedb/lancedb/issues/1112. It turned out that K-means is currently used internally, so I figured adding that context to the docs would be nice.
=> Explain vonoroi seed initalisation

rust/lancedb/src/arrow.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/query.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
This will make it easier for 3rd party integrations.  They simply need to implement `IntoArrow` for their types in order for those types to be used in ingestion.
=> feat(rust): add trait for incoming data

rust/ffi/node/src/index/vector.rs, rust/ffi/node/src/query.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/table.rs
This PR originated from a request to add `Serialize` / `Deserialize` to `lance_linalg::distance::DistanceType`.  However, that is a strange request for `lance_linalg` which shouldn't really have to worry about `Serialize` / `Deserialize`.  The problem is that `lancedb` is re-using `DistanceType` and things in `lancedb` do need to worry about `Serialize`/`Deserialize` (because `lancedb` needs to support remote client).
On the bright side, separating the two types allows us to independently document distance type and allows `lance_linalg` to make changes to `DistanceType` in the future without having to worry about backwards compatibility concerns.
=> feat: change DistanceType to be independent thing instead of resuing lance_linalg

python/python/lancedb/table.py, python/python/tests/test_huggingface.py
HuggingFace Dataset is written as arrow batches.
For DatasetDict, all splits are written with a "split" column appended.
=> feat(python): support writing huggingface dataset and dataset dict

nodejs/src/connection.rs, nodejs/src/table.rs, python/src/connection.rs, python/src/table.rs, rust/ffi/node/src/table.rs, rust/lancedb/src/arrow.rs, rust/lancedb/src/table.rs
In https://github.com/lancedb/lancedb/commit/2de226220b78c51b22319fb4fbc4678f4d269d65 I added a new `IntoArrow` trait for adding data into a table.  Unfortunately, it seems my approach for implementing the trait for "things that are already record batch readers" was flawed.  This PR corrects that flaw and, conveniently, removes the need to box readers at all (though it is ok if you do).
=> feat: introduce ArrowNative wrapper struct for adding data that is already a RecordBatchReader

node/src/index.ts, node/src/middleware.ts, node/src/remote/client.ts, node/src/remote/index.ts
Adds client-side middleware to LanceDB Node SDK to instrument HTTP Requests
Example - adding `x-request-id` request header:
```js
class HttpMiddleware {
constructor({ requestId }) {
this.requestId = requestId
}
onRemoteRequest(req, next) {
req.headers['x-request-id'] = this.requestId
return next(req)
}
}
const db = await lancedb.connect({
uri: 'db://remote-123',
apiKey: 'sk_...',
})
let tables = await db.withMiddleware(new HttpMiddleware({ requestId: '123' })).tableNames();
```
=> Node SDK Client middleware for HTTP Requests

.bumpversion.cfg, nodejs/npm/darwin-arm64/package.json, nodejs/npm/darwin-x64/package.json, nodejs/npm/linux-arm64-gnu/package.json, nodejs/npm/linux-x64-gnu/package.json, nodejs/npm/win32-x64-msvc/package.json, nodejs/package.json
The previous release failed to release nodejs because the nodejs version wasn't bumped.  This should fix that.
=> chore: add nodejs to bumpversion

docs/src/sql.md
Show that it is possible to use the DataFusion functions in the `WHERE` clause.
=> SQL Documentation includes DataFusion functions

node/src/remote/index.ts
This prevents an issue where users can do something like:
```js
db.createTable('my-table#123123')
```
The server has logic to determine that '#' character is not allowed in the table name, but currently this is being returned as 404 error because it routes to `/v1/my-table#123123/create` and `#123123/create` will not be parsed as part of path
=> ensure table names are uri encoded for tables

node/src/query.ts, node/src/test/test.ts
Changed the default value for search.limit to be 10
=> add a default value for search.limit to be consistent with python sdk

node/src/remote/client.ts, node/src/remote/index.ts, node/src/test/test.ts, node/src/util.ts, python/python/lancedb/remote/db.py
- make open table behaviour consistent:
- remote tables will check if the table exists by calling /describe and throwing an error if the call doesn't succeed
- this is similar to the behaviour for local tables where we will raise an exception when opening the table if the local dataset doesn't exist
- The table names are cached in the client with a TTL
- Also fixes a small bug where if the remote error response was deserialized from JSON as an object, we'd print it resulting in the unhelpful error message: `Error: Server Error, status: 404, message: Not Found: [object Object]`
=> BREAKING CHANGE: Check if remote table exists when opening (with caching)

.github/workflows/cargo-publish.yml, .github/workflows/pypi-publish.yml
* Python release has been running when we create a Node release. https://github.com/lancedb/lancedb/actions/runs/8635662585
* Rust is missing new enough compilers to check the kernels feature https://github.com/lancedb/lancedb/actions/runs/8635662578
=> ci: fix failures in release scripts

python/python/lancedb/rerankers/cohere.py
Fixes https://github.com/lancedb/lancedb/issues/1196
Cohere introduced a breaking change in their reranker API starting version 5.0.0. More context in discussion here https://github.com/cohere-ai/cohere-python/issues/446
=> fix(python): Update to latest cohere reranking api

docs/mkdocs.yml, docs/src/python/duckdb.md
This PR does the following:
- Fixes broken/outdated URLs
- Adds clarity to the way DuckDB/LanceDB integration works via Arrow
=> [docs] Fix broken links and clarify language in integrations docs

rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/lib.rs
The rust implementation of the remote client is not yet ready.  This is understandably confusing for users since it is enabled by default.  This PR disables it by default.  We can re-enable it when we are ready (even then it is not clear this is something that should be a default feature).
=> chore: disable the remote feature by default

nodejs/lancedb/connection.ts, nodejs/src/connection.rs, python/python/lancedb/db.py, python/python/lancedb/remote/db.py, python/python/lancedb/table.py, python/python/tests/test_db.py, python/src/connection.rs, rust/lancedb/src/connection.rs
This was already configurable in the rust API but it wasn't actually being passed down to the underlying dataset.  I added this option to both the async python API and the new nodejs API.
I also added this option to the synchronous python API.
I did not add the option to vectordb.
=> feat: allow the index_cache_size to be configured when opening a table

rust/lancedb/src/remote/db.rs
* create_table() was implemented for remote DB but the path was missing the trailing '/'
* It was not handling the 404 error response from phalanx and incorrectly returning a RemoteTable
=> fix: fix path on remote create_table and check for error response

python/src/error.rs, rust/lancedb/Cargo.toml, rust/lancedb/src/arrow.rs, rust/lancedb/src/error.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/polars_arrow_convertors.rs
https://github.com/lancedb/lancedb/issues/1099
Took the same general approach from: https://github.com/lancedb/lancedb/pull/1235. Instead of using high-level convertors  implemented in polars-arrow (with the arrow-rs feature flag, which adds a dependency on arrow-rs), I used convertors based on the C FFI to avoid dependency conflicts.
=> Implement convertors to and from Polars DataFrames in Rust SDK using convertors based on C FFI #1099

python/python/lancedb/__init__.py
It's confusing to users that keyword arguments from the async API like `storage_options` are accepted by `connect()`, but don't do anything. We should error if unknown arguments are passed instead.
=> fix(python): return ValueError if passed unknown args to `connect()`

python/python/lancedb/embeddings/utils.py
https://github.com/lancedb/lancedb/issues/1266#event-12703166915
This happens because openai API errors out with None values. The current log level didn't really print out the msg on screen. Changed the log level to warning, which better suits this case.
Also, retry loop can be disabled by setting `max_retries=0` (I'm not sure if we should also set this as the default behaviour as hitting api rate is quite common when ingesting large corpus)
```
func = get_registry().get("openai").create(max_retries=0)
````
=> Chore (python): Better retry loop logging when embedding api fails

README.md
URL in the README for LangChain is currently 404ing. Here's the new URL.
=> Update README.md to correct LangChain URL

.gitignore, rust/lancedb/examples/embedding_registry.rs, rust/lancedb/src/arrow.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/embeddings.rs, rust/lancedb/src/error.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs, rust/lancedb/tests/embedding_registry_test.rs
Todo:
**1 The python implementation just uses a global registry so it makes things a bit easier. I attached it to the db/connection to prevent future conflicts if running multiple connections/databases. I mostly modeled the registry & pattern off of datafusion's [FunctionRegistry](https://docs.rs/datafusion/latest/datafusion/execution/trait.FunctionRegistry.html). 
**2 Ideally, the user should be able to provide it's own registry entirely, but currently it just uses an in memory registry by default (_which isn't configurable_)
`rust/lancedb/examples/embedding_registry.rs` provides a thorough example of expected usage. 
---
Some additional notes:
This does not provide any of the out of box functionality that the python registry does.
_i.e there are no built-in embedding functions._ 
You …
=> feat: rust embedding registry

python/python/tests/test_fts.py
The syntax error was fixed in tantivy 0.22.0, so I changed the test case to something more wrong.
=> ci: better test for test_syntax

docs/src/embeddings/default_embedding_functions.md, python/pyproject.toml, python/python/lancedb/embeddings/__init__.py, python/python/lancedb/embeddings/ollama.py, python/python/tests/test_embeddings_slow.py
Following the docs [here](https://lancedb.github.io/lancedb/python/python/#lancedb.embeddings.openai.OpenAIEmbeddings) I've been trying to use ollama embedding via the OpenAI API interface, but unfortunately I couldn't get it to work (possibly related to https://github.com/ollama/ollama/issues/2416)
Given the popularity of ollama I thought it could be helpful to have a dedicated Ollama Embedding function in lancedb.
Very much welcome any thought on this or my code etc. Thanks!
=> Add ollama embeddings function

.github/labeler.yml, .github/release.yml, .github/workflows/dev.yml, release_process.md
* Enforce conventional commit PR titles
* Add automatic labelling of PRs
* Write down breaking change policy.
Left for another PR:
* Validation of breaking change version bumps. (This is complicated due to separate releases for Python and other package.)
=> ci: write down breaking change policy

nodejs/__test__/table.test.ts, nodejs/lancedb/table.ts, nodejs/src/table.rs, python/python/lancedb/_lancedb.pyi, python/python/lancedb/table.py, python/python/tests/test_table.py, python/src/table.rs, rust/ffi/node/src/table.rs, rust/lancedb/src/table.rs
The optimize function is pretty crucial for getting good performance when building a large scale dataset but it was only exposed in rust (many sync python users are probably doing this via to_lance today)
This PR adds the optimize function to nodejs and to python.
I left the function marked experimental because I think there will likely be changes to optimization (e.g. if we add features like "optimize on write").  I also only exposed the `cleanup_older_than` configuration parameter since this one is very commonly used and the rest have sensible defaults and we don't really know why we would recommend different values for these defaults anyways.
=> feat: add the optimize function to nodejs and async python

ci/bump_version.sh
I tried to do a stable release and it failed with:
```
Traceback (most recent call last):
File "/home/runner/work/lancedb/lancedb/ci/check_breaking_changes.py", line 20, in <module>
commits = repo.compare(args.base, args.head).commits
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/github/Repository.py", line 1133, in compare
headers, data = self._requester.requestJsonAndCheck("GET", f"{self.url}/compare/{base}...{head}", params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/github/Requester.py", line 548, in requestJsonAndCheck
return self.__check(*self.requestJson(verb, url, parameters, headers, input, …
```
=> fix: get the last stable release before we've added a new tag

.bumpversion.toml
Attempting to create a new minor version failed with:
```
Specified version (0.4.21-beta.0) does not match last tagged version (0.4.20) 
```
It seems the last release commit for rust/node was made without the new process and did not adjust bumpversion.toml correctly (or maybe bumpversion.toml did not exist at that time)
=> chore: sync bumpversion.toml with actual version

.github/workflows/upload_wheel/action.yml
The wheels are built to `WORKDIR/target/wheels` and the step was configured to look for them at `WORKDIR/python/target/wheels`.
=> chore: remove working-directory from pypi upload step

rust/lancedb/Cargo.toml, rust/lancedb/src/index.rs, rust/lancedb/src/index/vector.rs, rust/lancedb/src/table.rs
parse the index stats for scalar index - it is different from the index stats for vector index
=> fix: parse index_stats for scalar index

rust/lancedb/src/index.rs, rust/lancedb/src/index/vector.rs, rust/lancedb/src/table.rs
this also simplifies the code of creating index with macro
=> feat: support IVF_HNSW_PQ

python/python/lancedb/db.py, python/python/tests/test_db.py
- add `return` for `__enter__`
The buggy code didn't return the object, therefore it will always return None within a context manager:
```python
with await lancedb.connect_async("./.lancedb") as db:
```
(BTW, why not to design an async context manager?)
- add a unit test for Async connection context manager
- update return type of `AsyncConnection.open_table` to `AsyncTable`
Although type annotation doesn't affect the functionality, it is helpful for IDEs.
=> fix: the bug of async connection context manager

nodejs/__test__/registry.test.ts, nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/connection.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/embedding/index.ts, nodejs/lancedb/embedding/openai.ts, nodejs/lancedb/query.ts, nodejs/lancedb/sanitize.ts, nodejs/lancedb/table.ts, nodejs/package-lock.json, nodejs/package.json
while adding some more docs & examples for the new js sdk, i ran across a few compatibility issues when using different arrow versions. This should fix those issues.
=> feat(nodejs): add compatibility across arrow versions

.github/workflows/make-release-commit.yml
This doesn't actually block a python-only release since this step runs after the version bump has been pushed but it still would be nice for the git job to finish successfully.
=> ci: don't update package locks if we are not releasing node

node/src/index.ts, node/src/remote/index.ts, rust/lancedb/src/query.rs, rust/lancedb/src/table.rs, rust/lancedb/src/utils.rs
- changed the error msg for table.search with wrong query vector dim 
- added missing fields for listIndices and indexStats to be consistent with Python API - will make changes in node integ test
=> fix: error msg when query vector dim is wrong

node/src/index.ts
expose `status` returned by remote listIndices
=> fix: add status to remote listIndices return

java/core/lancedb-jni/src/ffi.rs
The Optional::isEmpty does not exist in java 8, so we should use isPresent instead
=> fix(java): the JVM crash when using jdk 8

node/src/index.ts, node/src/remote/index.ts
Changes new index stats fields in node client from snake case to camel case.
=> fix: use JS naming convention in new index stats fields

docs/src/fts.md, python/python/lancedb/fts.py, python/python/lancedb/table.py, python/python/tests/test_fts.py
Added the ability to specify tokenizer_name, when creating a full text search index using tantivy. This enables the use of language specific stemming. 
Also updated the [guide on full text search](https://lancedb.github.io/lancedb/fts/) with a short section on choosing tokenizer.
Fixes #1315
=> feat: enable stemming

docs/src/guides/tables.md
Currently, the whole polars section is formatted as a code block: https://lancedb.github.io/lancedb/guides/tables/#from-a-polars-dataframe
This PR fixes the formatting.
=> docs: fixes polars formatting in docs

docs/src/embeddings/default_embedding_functions.md
* `table.add` requires `data` parameter on the docs page regarding use of embedding models from HF
* also changed the name of example class from `TextModel`  to `Words` since that is what is used as parameter in the `db.create_table` call
* Per https://lancedb.github.io/lancedb/python/python/#lancedb.table.Table.add
=> docs: addresses typos in HF embedding example docs

nodejs/Cargo.toml, nodejs/package-lock.json, nodejs/package.json, nodejs/src/connection.rs, nodejs/src/iterator.rs, nodejs/src/merge.rs, nodejs/src/query.rs, nodejs/src/table.rs
this bumps napi version to 2.16 which contains a few bug fixes.
Additionally, it adds `catch_unwind` to any method that may unintentionally panic. 
`catch_unwind` will unwind the panics and return a regular JS error instead of panicking.
=> feat(nodejs): catch unwinds in node bindings

nodejs/__test__/registry.test.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/embedding/openai.ts, nodejs/lancedb/embedding/registry.ts
previously the `registry` would return `undefined | EmbeddingFunction` even for built in functions such as "openai"
now it'll return the correct type for `getRegistry().get("openai")
as well as pass in the correct options type to `create`
```ts
const options: {model: 'not-a-real-model'}
// this'd compile just fine, but result in runtime error
const openai: EmbeddingFunction | undefined = getRegistry().get("openai").create(options)
// this'd also compile fine
const openai: EmbeddingFunction | undefined = getRegistry().get("openai").create({MODEL: ''})
```
```ts
const options: {model: 'not-a-real-model'}
const openai: OpenAIEmbeddingFunction = getRegistry().get("openai").create(options)
// Type '"not-a-real-model"' is not assignable to type '"text-embedding-ada-002" | …
```
=> feat(nodejs): add better typehints for registry

nodejs/package.json
fyi, this should have no breaking changes as npm is opt-out instead of opt-in when resolving dependencies
all peer and optional dependencies get installed by default, so users need to manually opt out. 
`npm i --omit optional --omit peer`
=> chore(nodejs): make opean optional, and apache-arrow a peer dep

nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/query.ts, nodejs/lancedb/remote/table.ts, nodejs/lancedb/table.ts
so this was annoying me when writing the docs. 
for a `search` query, one needed to chain `async` calls.
```ts
const res = await (await tbl.search("greetings")).toArray()
```
now the promise will be deferred until the query is collected, leading to a more functional API
```ts
const res = await tbl.search("greetings").toArray()
```
=> feat(nodejs): make tbl.search chainable

python/python/lancedb/__init__.py
Feel free to close if this is a distraction, but untyped keywords in lance.connect is throwing pylance errors in strict mode.
=> chore: typing for lance.connect

.github/workflows/node.yml, .github/workflows/npm-publish.yml, ci/manylinux_node/Dockerfile
* Labelled jobs `vectordb` and `lancedb` so it's clear which package they are for
* Fix permission issue in aarch64 Linux `vectordb` build that has been blocking release for two months.
* Added Slack notifications for failure of these publish jobs.
=> ci: fix vectordb release process

docs/src/embeddings/default_embedding_functions.md, python/python/lancedb/embeddings/sentence_transformers.py
Closes #1285 
Added trust_remote_code to the SentenceTransformerEmbeddings class.
Defaults to `False`
=> fix: added support for trust_remote_code

nodejs/__test__/arrow.test.ts, nodejs/__test__/registry.test.ts, nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/package-lock.json, nodejs/package.json
previously if you tried to install both vectordb and @lancedb/lancedb, you would get a peer dependency issue due to `vectordb` requiring `14.0.2` and `@lancedb/lancedb` requiring `15.0.0`. now `@lancedb/lancedb` should just work with any arrow version 13-17
=> fix(nodejs): lancedb arrow dependency

docs/src/basic.md
I noticed that setting up a simple project with [Yarn](https://yarnpkg.com/) failed because unlike others [npm, pnpm, bun], yarn does not automatically resolve peer dependencies, so i added a quick note about it in the installation guide.
=> docs: add installation note about yarn

nodejs/lancedb/remote/client.ts, nodejs/lancedb/remote/connection.ts
Correct the timeout argument to `connect` in @lancedb/lancedb node SDK. `RemoteConnectionOptions` specified two fields `connectionTimeout` and `readTimeout`, probably to be consistent with the python SDK, but only `connectionTimeout` was being used and it was passed to axios in such a way that this covered the enture remote request (connect + read). This change adds a single parameter `timeout` which makes the args to `connect` consistent with the legacy vectordb sdk.
BREAKING CHANGE: This is a breaking change b/c users who would have previously been passing `connectionTimeout` will now be expected to pass `timeout`.
=> feat!: correct timeout argument lancedb nodejs sdk

python/python/lancedb/db.py, python/python/lancedb/remote/db.py, python/python/lancedb/remote/table.py, python/python/lancedb/table.py, python/python/tests/test_huggingface.py
Closes #1383
When creating a table from a HuggingFace dataset, infer the arrow schema directly
=> fix: infer schema from huggingface dataset

docs/src/embeddings/default_embedding_functions.md
This PR adds a missing whitespace before a markdown table in the documentation. This issue causes the table to not render properly in mkdocs, while it does render properly in GitHub's markdown viewer.
- Added a single line of whitespace before the markdown table to ensure proper rendering in mkdocs.
- I wasn't able to test this fix in the mkdocs environment, but it should be safe as it only involves adding whitespace which won't break anything.
---
Cohere supports following input types:
| Input Type               | Description                          |
|-------------------------|---------------------------------------|
| "`search_document`"     | Used for embeddings stored in a vector|
|                         | database for search use-cases.        |
| "`search_query`"        | Used …
=> docs: add missing whitespace before markdown table to fix rendering issue

Cargo.toml
To use the same version with lance
=> chore: upgrade object_store to 0.10.2

python/python/lancedb/embeddings/instructor.py, python/python/lancedb/embeddings/transformers.py, python/python/lancedb/query.py, python/python/lancedb/rerankers/colbert.py, python/python/lancedb/rerankers/cross_encoder.py, python/python/tests/test_rerankers.py
- Update ColBertReranker architecture: The current implementation doesn't use the right arch. This PR uses the implementation in Rerankers library. Fixes https://github.com/lancedb/lancedb/issues/1546
Benchmark diff (hit rate):
Hybrid - 91 vs 87
reranked vector - 85 vs 80
- Reranking in FTS is basically disabled in main after last week's FTS updates. I think there's no blocker in supporting that? 
- Allow overriding accelerators: Most transformer based Rerankers and Embedding automatically select device. This PR allows overriding those settings by passing `device`. Fixes: https://github.com/lancedb/lancedb/issues/1487
=> chore(python): update Colbert architecture and minor improvements

docs/src/reranking/answerdotai.md, python/python/lancedb/embeddings/sentence_transformers.py, python/python/lancedb/embeddings/transformers.py, python/python/lancedb/rerankers/__init__.py, python/python/lancedb/rerankers/answerdotai.py, python/python/lancedb/rerankers/base.py, python/python/lancedb/rerankers/cohere.py, python/python/lancedb/rerankers/colbert.py, python/python/lancedb/rerankers/cross_encoder.py, python/python/lancedb/rerankers/jinaai.py, python/python/lancedb/rerankers/linear_combination.py, python/python/lancedb/rerankers/openai.py, python/python/lancedb/rerankers/rrf.py, python/python/tests/test_rerankers.py
This PR:
- Adds missing license headers
- Integrates with answerdotai Rerankers package
- Updates ColbertReranker to subclass answerdotai package. This is done to keep backwards compatibility as some users might be used to importing ColbertReranker directly
- Set `trust_remote_code` to ` True` by default in CrossEncoder and sentence-transformer based rerankers
=> feat: add answerdotai rerankers support and minor improvements

python/python/lancedb/query.py, python/python/lancedb/remote/table.py, python/python/lancedb/table.py, python/python/tests/test_fts.py, python/src/index.rs
Before this we ignored the `fts_columns` parameter, and for now we support to search on only one column, it could lead to an error if we have multiple indexed columns for FTS
=> fix: specify column to search for FTS

docs/src/embeddings/available_embedding_models/multimodal_embedding_functions/imagebind_embedding.md, docs/src/embeddings/available_embedding_models/multimodal_embedding_functions/openclip_embedding.md
Docs used `get_registry.get(...)` whereas what works is `get_registry().get(...)`. Fixing the two instances I found. I tested the open clip version by trying it locally in a Jupyter notebook.
=> docs: fix get_registry() usage

docs/src/concepts/index_hnsw.md
Though the markdown can be rendered well on GitHub (GFM style?), but it seems that it's required to insert a blank line between a paragraph and a list block to make it render well with `mkdocs`?
see also the web page: https://lancedb.github.io/lancedb/concepts/index_hnsw/
=> docs: added a blank line between a paragraph and a list block

python/python/lancedb/query.py, python/python/tests/test_table.py
first off, apologies for any folly since i'm new to contributing to lancedb. this PR is the continuation of [a discord thread](https://discord.com/channels/1030247538198061086/1030247538667827251/1278844345713299599):
here's the lance db search query i'd like to run:
```
def search(phrase):
logger.info(f'Searching for phrase: {phrase}')
phrase_embedding = get_embedding(phrase)
df = (table.search((phrase_embedding, phrase), query_type='hybrid')
.limit(10).to_list())
logger.info(f'Success search with row count: {len(df)}')
search('howdy (howdy)')
search('howdy(howdy)')
```
the second search fails due to `ValueError: Syntax Error: howdy(howdy)`
i saw on the [docs](https://lancedb.github.io/lancedb/fts/#phrase-queries-vs-terms-queries) that i can use `phrase_query()` to [enable a …
=> feat: enable phrase_query(bool) for hybrid search queries

Cargo.toml, nodejs/__test__/connection.test.ts, nodejs/lancedb/connection.ts, nodejs/lancedb/table.ts, nodejs/package-lock.json, nodejs/src/connection.rs, nodejs/src/table.rs, python/python/lancedb/_lancedb.pyi, python/python/lancedb/db.py, python/python/lancedb/table.py, python/python/tests/test_db.py, python/src/connection.rs, python/src/table.rs, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/table.rs
The new V2 manifest path scheme makes discovering the latest version of a table constant time on object stores, regardless of the number of versions in the table. See benchmarks in the PR here: https://github.com/lancedb/lance/pull/2798
Closes #1583
=> feat: add flag to enable faster manifest paths

python/pyproject.toml, python/python/lancedb/embeddings/utils.py, python/python/tests/test_embeddings.py
The `ratelimiter` package hasn't been updated in ages and is no longer maintained. This PR removes the dependency on `ratelimiter` and replaces it with a custom rate limiter implementation.
=> fix(python): remove unmaintained ratelimiter dependency

rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs
* Adding a simple test facility, which allows you to mock a single endpoint at a time with a closure.
* Implementing all the database-level endpoints
Table-level APIs will be done in a follow up PR.
=> feat: implement Remote connection for LanceDB Rust

python/python/lancedb/util.py, python/python/tests/test_util.py
resolves #1429 
(python)
```python
-    return f"'{value}'"
+    return f'"{value}"'
```
=> fix: unterminated string literal on table update

python/python/lancedb/remote/client.py, python/python/tests/test_remote_client.py
Allow `RemoteLanceDBClient` to be used as context manager
=> chore: make remote client a context manager

Cargo.toml, nodejs/__test__/connection.test.ts, nodejs/lancedb/connection.ts, nodejs/src/connection.rs, nodejs/src/table.rs, python/pyproject.toml, python/python/lancedb/db.py, python/python/tests/test_db.py, rust/lancedb/src/connection.rs, rust/lancedb/src/embeddings/sentence_transformers.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
BREAKING CHANGE: default file format changed to Lance v2.0.
Upgrade Lance to 0.18.0
Change notes: https://github.com/lancedb/lance/releases/tag/v0.18.0
=> feat!: upgrade Lance to 0.18.0

docs/src/reranking/linear_combination.md, docs/src/reranking/rrf.md, python/python/lancedb/query.py, python/python/lancedb/rerankers/base.py, python/python/lancedb/rerankers/linear_combination.py, python/python/lancedb/rerankers/util.py, python/python/tests/test_rerankers.py
- Enforce all rerankers always return _relevance_score. This was already loosely done in tests before but based on user feedback its better to always have _relevance_score present in all reranked results
- Deprecate LinearCombinationReranker in docs. And also fix a case where it would not return _relevance_score if one result set was missing
=> feat!: enforce all rerankers always return relevance score & deprecate linear combination fixes

python/python/lancedb/table.py, python/python/tests/test_table.py
Right now when passing vector and query explicitly for hybrid search , vector_column_name is not deduced. (https://lancedb.github.io/lancedb/hybrid_search/hybrid_search/#hybrid-search-in-lancedb ). Because vector and query can be both none when initialising the QueryBuilder in this case. This PR forces deduction of query type if it is set to "hybrid"
=> fix(python): force deduce vector column name if running explicit hybrid query

rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
We frequently need to recover this uri so exposing it to make it easy
=> feat: expose underlying dataset uri of the table

node/src/index.ts, node/src/query.ts, node/src/remote/client.ts, node/src/remote/index.ts, node/src/test/test.ts, nodejs/__test__/table.test.ts, nodejs/lancedb/index.ts, nodejs/src/table.rs, python/python/lancedb/table.py, python/python/tests/test_index.py, python/src/index.rs, python/src/table.rs, rust/ffi/node/src/table.rs, rust/lancedb/src/index.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
BREAKING CHANGE: the return value of `index_stats` method has changed and all `index_stats` APIs now take index name instead of UUID. Also several deprecated index statistics methods were removed.
* Removes deprecated methods for individual index statistics
* Aligns public `IndexStatistics` struct with API response from LanceDB Cloud.
* Implements `index_stats` for remote Rust SDK and Python async API.
=> feat: remote index stats

docs/src/embeddings/available_embedding_models/text_embedding_functions/huggingface_embedding.md, python/python/lancedb/embeddings/transformers.py
Resovles #1709. Adds `trust_remote_code` as a parameter to the `TransformersEmbeddingFunction` class with a default of False. Updated relevant documentation with the same.
=> feat(python): add support for trust_remote_code in hf embeddings

python/python/tests/test_index.py, rust/lancedb/src/index.rs, rust/lancedb/src/table.rs
Fixes https://github.com/lancedb/lancedb/issues/1711
Doesn't address this https://github.com/lancedb/lance/issues/2039
Instead we load the index statistics, which seems to contain the index type. However, this involves more IO than previously. I'm not sure whether we care that much. If we do, we can fix that upstream Lance issue.
=> fix: `list_indices` returns correct index type

python/Cargo.toml, python/python/lancedb/__init__.py, python/python/lancedb/remote/__init__.py, python/python/tests/test_remote_db.py, python/src/connection.rs, rust/lancedb/src/remote/client.rs
Closes [#1638](https://github.com/lancedb/lancedb/issues/1638)
This just binds the Python Async client to the Rust remote client.
=> feat(python): bind python async remote client to rust client

rust/lancedb/src/remote/table.rs, rust/lancedb/src/remote/util.rs
A few bugs uncovered by integration tests:
* We didn't prepend `/v1` to the Table endpoint URLs
* `/create_index` takes `metric_type` not `distance_type`. (This is also an error in the OpenAPI docs.)
* `/create_index` expects the `metric_type` parameter to always be lowercase.
* We were writing an IPC file message when we were supposed to send an IPC stream message.
=> fix(rust): remote SDK bugs

python/python/lancedb/remote/client.py, python/python/lancedb/remote/errors.py, python/python/tests/test_db.py, python/python/tests/test_remote_db.py, python/src/error.rs, rust/lancedb/src/error.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs
* Adds nicer errors to remote SDK, that expose useful properties like `request_id` and `status_code`.
* Makes sure the Python tracebacks print nicely by mapping the `source` field from a Rust error to the `__cause__` field.
=> feat: better errors for remote SDK

.bumpversion.toml, node/package-lock.json, node/package.json, node/src/integration_test/test.ts, node/src/query.ts, node/src/remote/index.ts, node/src/test/test.ts
We weren't bumping the version, so when users downloaded our package from npm, they were getting the old binaries.
=> fix(node): add native packages to bump version

docs/src/guides/storage.md
Clarifies infrastructure requirements for S3 Express One Zone to avoid a possible misunderstanding.
When I read the docs, I was thinking: S3 Express One Zone would work only with EC2.
=> docs: clarify infrastructure requirements for S3 Express One Zone

docs/mkdocs.yml, docs/src/styles/extra.css
I noted that there are no permanent links in the docs. Adapted the current best solution from https://github.com/squidfunk/mkdocs-material/discussions/3535. It adds a GitHub-like chain icon to the left of each heading (right on mobile) and does not impact SEO unlike the default solution with pilcrow char `¶` that might show up on google search results.
=> docs: add permanent link chain icon to headings without impacting SEO

python/python/lancedb/query.py, python/python/lancedb/remote/__init__.py, python/python/lancedb/remote/table.py
Add `fast_search` parameter to query builder and remote table to support skipping flat search in remote search
=> feat: allow fast_search on python remote table

python/pyproject.toml, python/python/lancedb/embeddings/utils.py, python/python/tests/test_embeddings.py
fixes https://github.com/lancedb/lancedb/issues/1480
https://github.com/invl/retry has not had an update in 8 years, one if its sub-dependencies via requirements.txt (https://github.com/pytest-dev/py) is no longer maintained and has a high severity vulnerability (CVE-2022-42969).
retry is only used for a single function in the python codebase for a deprecated helper function `with_embeddings`, which was created for an older tutorial (https://github.com/lancedb/lancedb/pull/12) [but is now deprecated](https://lancedb.github.io/lancedb/embeddings/legacy/).
i backported a limited range of functionality of the `@retry()` decorator directly into lancedb so that we no longer have a dependency to the `retry` package.
```
/Users/james/src/lancedb/python $ ruff check .
All checks passed! …
```
=> fix(python): remove dependency on retry package

docs/src/javascript/README.md, docs/src/javascript/classes/DefaultWriteOptions.md, docs/src/javascript/classes/LocalConnection.md, docs/src/javascript/classes/LocalTable.md, docs/src/javascript/classes/MakeArrowTableOptions.md, docs/src/javascript/classes/OpenAIEmbeddingFunction.md, docs/src/javascript/classes/Query.md, docs/src/javascript/enums/IndexStatus.md, docs/src/javascript/enums/MetricType.md, docs/src/javascript/enums/WriteMode.md, docs/src/javascript/interfaces/AwsCredentials.md, docs/src/javascript/interfaces/CleanupStats.md, docs/src/javascript/interfaces/ColumnAlteration.md, docs/src/javascript/interfaces/CompactionMetrics.md, docs/src/javascript/interfaces/CompactionOptions.md, docs/src/javascript/interfaces/Connection.md, docs/src/javascript/interfaces/ConnectionOptions.md, docs/src/javascript/interfaces/CreateTableOptions.md, docs/src/javascript/interfaces/EmbeddingFunction.md, docs/src/javascript/interfaces/IndexStats.md, docs/src/javascript/interfaces/IvfPQIndexConfig.md, docs/src/javascript/interfaces/MergeInsertArgs.md, docs/src/javascript/interfaces/Table.md, docs/src/javascript/interfaces/UpdateArgs.md, docs/src/javascript/interfaces/UpdateSqlArgs.md, docs/src/javascript/interfaces/VectorIndex.md, docs/src/javascript/interfaces/WriteOptions.md, docs/src/javascript/modules.md, node/src/index.ts, node/src/remote/index.ts
`indexStats` still referenced UUID even though in https://github.com/lancedb/lancedb/pull/1702 we changed it to take name instead.
=> docs(node): update `indexStats` signature and regenerate docs

rust/lancedb/src/table/dataset.rs
Closes #1741
If we checkout a version, we need to make a `HEAD` request to get the size of the manifest. The new `checkout_latest()` code path can skip this IOP. This makes the refresh slightly faster.
=> perf: eliminate iop in refresh

Cargo.toml, docs/mkdocs.yml, docs/src/troubleshooting.md, nodejs/Cargo.toml, nodejs/__test__/remote.test.ts, nodejs/package.json, nodejs/src/connection.rs, nodejs/src/error.rs, nodejs/src/lib.rs, nodejs/src/merge.rs, nodejs/src/query.rs, nodejs/src/table.rs, python/Cargo.toml, rust/lancedb/src/remote/client.rs
This exposes the `LANCEDB_LOG` environment variable in node, so that users can now turn on logging.
In addition, fixes a bug where only the top-level error from Rust was being shown. This PR makes sure the full error chain is included in the error message. In the future, will improve this so the error chain is set on the [cause](https://nodejs.org/api/errors.html#errorcause) property of JS errors https://github.com/lancedb/lancedb/issues/1779
Fixes #1774
=> feat(node): enable logging and show full errors

rust/lancedb/src/index.rs, rust/lancedb/src/table.rs
When running `index_stats()` for an FTS index, users would get the deserialization error:
```
InvalidInput { message: "error deserializing index statistics: unknown variant `Inverted`, expected one of `IvfPq`, `IvfHnswPq`, `IvfHnswSq`, `BTree`, `Bitmap`, `LabelList`, `FTS` at line 1 column 24" }
```
=> fix: index_stats works for FTS indices

rust/lancedb/src/remote.rs, rust/lancedb/src/remote/table.rs
Fixes several minor issues with Rust remote SDK:
* Delete uses `predicate` not `filter` as parameter
* Update does not return the row value in remote SDK
* Update takes tuples
* Content type returned by query node is wrong, so we shouldn't validate it. https://github.com/lancedb/sophon/issues/2742
* Data returned by query endpoint is actually an Arrow IPC file, not IPC stream.
=> fix(rust): fix delete, update, query in remote SDK

nodejs/__test__/table.test.ts, nodejs/lancedb/query.ts, nodejs/src/query.rs, python/python/lancedb/query.py, python/python/tests/test_query.py, python/src/query.rs
Sometimes it is acceptable to users to only search indexed data and skip and new un-indexed data. For example, if un-indexed data will be shortly indexed and they don't mind the delay. In these cases, we can save a lot of CPU time in search, and provide better latency. Users can activate this on queries using `fast_search()`.
=> feat: `fast_search` in Python and Node

rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs
* `open_table` uses `POST` not `GET`
* `update` uses `predicate` key not `only_if`
* For FTS search, vector cannot be omitted. It must be passed as empty.
* Added logging of JSON request bodies to debug level logging.
=> fix(rust): fix update, open_table, fts search in remote client

nodejs/__test__/table.test.ts, nodejs/lancedb/query.ts, nodejs/src/query.rs, python/python/lancedb/query.py, python/python/tests/test_query.py, python/src/query.rs, rust/lancedb/src/remote/table.rs
Needed to support hybrid search in Remote SDK.
=> feat(python,node): support with_row_id in Python and remote

rust/lancedb/src/index.rs
we don't really need these trait in lancedb, but all fields in `Index` implement the 2 traits, so do it for possibility to use `Index` somewhere
=> chore: impl Debug & Clone for Index params

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [LanceDB Guru](https://gurubase.io/g/lancedb) to Gurubase. LanceDB Guru uses the data from this repo and data from the [docs](https://lancedb.github.io/lancedb/) to answer questions by leveraging the LLM.
In this PR, I showcased the "LanceDB Guru", which highlights that LanceDB now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if …
=> docs: introducing LanceDB Guru on Gurubase.io

nodejs/__test__/table.test.ts, nodejs/lancedb/query.ts, nodejs/package-lock.json, nodejs/src/query.rs, python/python/lancedb/query.py, python/python/tests/test_remote_db.py, python/src/query.rs, rust/lancedb/src/query.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
Allows users to pass multiple query vector as part of a single query plan. This just runs the queries in parallel without any further optimization. It's mostly a convenience.
Previously, I think this was only handled by the sync Python remote API. This makes it common across all SDKs.
Closes https://github.com/lancedb/lancedb/issues/1803
```python
>>> import lancedb
>>> import asyncio
>>> 
>>> async def main():
...     db = await lancedb.connect_async("./demo")
...     table = await db.create_table("demo", [{"id": 1, "vector": [1, 2, 3]}, {"id": 2, "vector": [4, 5, 6]}], mode="overwrite")
...     return await table.query().nearest_to([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [4.0, 5.0, 6.0]]).limit(1).to_pandas()
... 
>>> asyncio.run(main())
query_index  id           vector  _distance
0 …
```
=> feat: search multiple query vectors as one query

python/python/lancedb/query.py, python/python/lancedb/remote/table.py, python/python/tests/test_remote_db.py, python/python/tests/test_table.py
Support sending empty query types to remote lancedb. also include offset and limit, where were previously omitted.
=> feat: support remote empty query

nodejs/examples/sentence-transformers.test.ts, nodejs/lancedb/embedding/index.ts, nodejs/lancedb/embedding/registry.ts, nodejs/package.json
BREAKING CHANGE: openai and huggingface now have separate entrypoints.
Closes [#1624](https://github.com/lancedb/lancedb/issues/1624)
=> fix(node): make openai and huggingface optional dependencies

.github/workflows/nodejs.yml, Cargo.toml, docs/src/guides/tables.md, nodejs/__test__/table.test.ts, nodejs/lancedb/arrow.ts, python/python/lancedb/table.py, python/python/tests/test_embeddings.py, python/python/tests/test_table.py
* Test that we can insert subschemas (omit nullable columns) in Python.
* More work is needed to support this in Node. See: https://github.com/lancedb/lancedb/issues/1832
* Test that we can insert data with nullable schema but no nulls in non-nullable schema.
* Add `"null"` option for `on_bad_vectors` where we fill with null if the vector is bad.
* Make null values not considered bad if the field itself is nullable.
=> feat: flexible null handling and insert subschemas in Python

python/Cargo.toml, rust/lancedb/Cargo.toml
Hello, this is a simple PR that supports `rustls-tls` feature.
The `reqwest`\`s default TLS `default-tls` is enabled by default, to dismiss the side-effect.
The user can use `rustls-tls` like this:
```toml
lancedb = { version = "*", default-features = false, features = ["rustls-tls"] }
```
=> feat: add support for rustls

python/python/lancedb/query.py, python/python/lancedb/table.py, python/python/tests/test_query.py
Fix the type hints of `nearest_to` method, and raise `ValueError` when the input is None
=> feat(python): check vector query is not None

docs/src/guides/tables.md
PR fixes the `migration.md` reference in `docs/src/guides/tables.md`. On the way, it also fixes some typos found in that document.
=> docs: update migration reference

Cargo.toml, python/pyproject.toml, rust/lancedb/src/table.rs
Bump lance version.
Upstream change log: https://github.com/lancedb/lance/releases/tag/v0.20.0-beta.2
=> feat: bump lance to 0.20.0b2

node/package.json
I missed targets when manually merging draft PR to updated main
I was copying from: https://github.com/lancedb/lancedb/pull/1816/files#diff-d6e19f28e97cfeda63a9bd9426f10f1d2454eeed375ee1235e8ba842ceeb46a0
fixes:
error: Rust target x86_64-unknown-linux-musl not found in package.json.
=> ci: musl missing node/package.json targets

python/pyproject.toml, python/python/lancedb/remote/background_loop.py, python/python/lancedb/remote/db.py, python/python/lancedb/remote/table.py, python/python/tests/test_remote_db.py
Users who call the remote SDK from code that uses futures (either `ThreadPoolExecutor` or `asyncio`) can get odd errors like:
```
Traceback (most recent call last):
File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x7cfe94cdc900> is already entered
```
This PR fixes that by executing all LanceDB futures in a dedicated thread pool running on a background thread. That way, it doesn't interact with their threadpool.
=> fix(python): run remote SDK futures in background thread

Cargo.toml, python/pyproject.toml
Bump lance version.
Upstream change log:
https://github.com/lancedb/lance/releases/tag/v0.20.0-beta.3
=> feat: bump lance to 0.20.0b3

.github/workflows/npm-publish.yml
We already do this for `gnu` builds, we should do this also for `musl` builds.
=> ci: use correct runner for vectordb

rust/lancedb/src/connection.rs, rust/lancedb/src/remote/db.rs
Support passing modes "overwrite" and "exist_ok" when creating a remote table.
=> feat: support overwrite and exist_ok mode for remote create_table

docs/mkdocs.yml, docs/src/python/python.md
I found the signatures difficult to read and the parameter section not very space efficient.
=> docs: improve style and introduction to Python API docs

.github/workflows/npm-publish.yml, ci/build_linux_artifacts.sh, ci/manylinux_node/build_vectordb.sh
fixes that all `neon pack-build` packs are named `vectordb-linux-x64-musl-*.tgz` even when cross-compiling
adds 2nd param:
`TARGET_TRIPLE=${2:-x86_64-unknown-linux-gnu}`
`npm run pack-build -- -t $TARGET_TRIPLE`
=> ci: linux: specify target triple for `neon pack-build` (vectordb)

.github/workflows/pypi-publish.yml, .github/workflows/upload_wheel/action.yml
Fix failing python release for windows: https://github.com/lancedb/lancedb/actions/runs/12019637086/job/33506642964
Also updates pkginfo to fix twine build as suggested here: https://github.com/pypi/warehouse/issues/15611
failing release: https://github.com/lancedb/lancedb/actions/runs/12091344173/job/33719622146
=> ci: fix failing python release

.github/workflows/npm-publish.yml, ci/manylinux_node/build_vectordb.sh, ci/sysroot-aarch64-pc-windows-msvc.sh, ci/sysroot-x86_64-pc-windows-msvc.sh
`npm run pack-build -- -t $TARGET_TRIPLE`
was needed instead of
`npm run pack-build -t $TARGET_TRIPLE`
https://github.com/lancedb/lancedb/pull/1889
some documentation about `*-pc-windows-msvc` cross-compilation (from alpine):
https://github.com/lancedb/lancedb/pull/1831#issuecomment-2497156918
only `arm64` in `matrix` config is used
since `x86_64` built by `runs-on: windows-2022` is working
=> ci: aarch64-pc-windows-msvc

rust/lancedb/src/remote/client.rs
Add remote database folder prefix
support db://bucket/path/to/folder/
=> feat: add remote db uri path with folder prefix

python/python/lancedb/table.py, rust/lancedb/src/table.rs
Previously, whenever `Table.add()` was called, we would write and re-open the underlying dataset. This was bad for performance, as it reset the table cache and initiated a lot of IO. It also could be the source of bugs, since we didn't necessarily pass all the necessary connection options down when re-opening the table.
Closes #1655
=> perf: re-use table instance during write

rust/lancedb/src/connection.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/query.rs
* One doctest was running for > 60 seconds in CI, since it was (unsuccessfully) trying to connect to LanceDB Cloud.
* Fixed the example for `Query::full_text_query()`, which was incorrect.
=> docs(rust): fix doctests

.github/workflows/docs.yml
For https://github.blog/changelog/2024-12-05-deprecation-notice-github-pages-actions-to-require-artifacts-actions-v4-on-github-com/
=> ci: upgrade version of upload-pages-artifact and deploy-pages

python/python/lancedb/query.py, python/python/tests/test_query.py
User reported on Discord, when using `table.vector_search([np.float16(1.0), np.float16(2.0), ...])`, it yields `TypeError: 'numpy.float16' object is not iterable`
=> fix: support list of numpy f16 floats as query vector

.github/workflows/rust.yml, Cargo.toml, rust-toolchain.toml, rust/lancedb/Cargo.toml, rust/lancedb/src/query.rs
* Upgrades our toolchain file to v1.83.0, since many dependencies now have MSRV of 1.81.0
* Reverts Rust changes from #1946 that were working around this in a dumb way
* Adding an MSRV check
* Reduce MSRV back to 1.78.0
=> ci(rust): check MSRV and upgrade toolchain

python/python/lancedb/query.py, python/python/lancedb/table.py, python/python/tests/test_db.py
Hi lancedb team,
This PR adds the `bypass_vector_index` logic to the sync API, as described in [Issue #535](https://github.com/lancedb/lancedb/issues/535). (Closes #535).
Iv'e implemented it only for the regular vector search. If you think it should also be supported for FTS, Hybrid, or Empty queries and for the cloud solution, please let me know, and I’ll be happy to extend it.
Since there’s no `CONTRIBUTING.md` or contribution guidelines, I opted for the simplest implementation to get this started.
Looking forward to your feedback!
Thanks!
=> feat(python): add `bypass_vector_index` to sync api

python/python/lancedb/db.py, python/python/tests/test_db.py
- feat(db): add `ignore_missing` to async `drop_table` method
Fixes #1951
=> feat(python): add `ignore_missing` to the async drop_table() method

docs/src/python/python.md, docs/src/search.md, docs/test/md_testing.py, nodejs/src/util.rs, python/python/lancedb/index.py, python/python/lancedb/table.py, python/python/tests/docs/test_binary_vector.py, python/python/tests/test_index.py, python/src/index.rs, python/src/util.rs, rust/lancedb/src/index.rs, rust/lancedb/src/index/vector.rs, rust/lancedb/src/table.rs, rust/lancedb/src/utils.rs
binary vectors and hamming distance can work on only IVF_FLAT, so introduce them all in this PR.
=> feat: support IVF_FLAT, binary vectors and hamming distance

.github/workflows/npm-publish.yml
We upgraded the toolchain in #1960, but didn't realize we hardcoded it in `npm-publish.yml`. I found if I just removed the hard-coded toolchain, it selects the correct one.
This didn't fully fix Windows Arm, so I created a follow-up issue here: https://github.com/lancedb/lancedb/issues/1975
=> ci(node): remove hardcoded toolchain from typescript release build

nodejs/Cargo.toml, nodejs/__test__/arrow.test.ts, nodejs/__test__/rerankers.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/index.ts, nodejs/lancedb/query.ts, nodejs/lancedb/rerankers/index.ts, nodejs/lancedb/rerankers/rrf.ts, nodejs/src/lib.rs, nodejs/src/query.rs, nodejs/src/rerankers.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/query.rs, rust/lancedb/src/query/hybrid.rs, rust/lancedb/src/rerankers.rs, rust/lancedb/src/rerankers/rrf.rs
Support hybrid search in both rust and node SDKs.
- Adds a new rerankers package to rust LanceDB, with the implementation of the default RRF reranker
- Adds a new hybrid package to lancedb, with some helper methods related to hybrid search such as normalizing scores and converting score column to rank columns
- Adds capability to LanceDB VectorQuery to perform hybrid search if it has both a nearest vector and full text search parameters.
- Adds wrappers for reranker implementations to nodejs SDK.
Additional rerankers will be added in followup PRs
https://github.com/lancedb/lancedb/issues/1921
---
Notes about how the rust rerankers are wrapped for calling from JS:
I wanted to keep the core reranker logic, and the invocation of the reranker by the query code, in Rust. This aligns with the …
=> feat: add hybrid search to node and rust SDKs

python/python/tests/test_fts.py, python/src/query.rs
it reports error `AttributeError: 'builtins.FTSQuery' object has no attribute 'select_columns'`
because we missed `select_columns` method in rust
=> fix: selecting columns failed on FTS and hybrid search

docs/src/fts.md
Fix
```
Cannot find name 'queryType'.ts(2304)
any
```
=> docs: fix full-text search (Native FTS) TypeScript doc error

.github/workflows/make-release-commit.yml, ci/validate_stable_lance.py
Accidentally referenced a preview release in our stable release of LanceDB. This adds a CI check to prevent that.
=> ci: prevent stable release with preview lance

python/python/lancedb/db.py, python/python/lancedb/embeddings/registry.py, python/python/lancedb/query.py, python/python/lancedb/table.py, python/python/lancedb/util.py, python/python/tests/docs/test_binary_vector.py, python/python/tests/docs/test_guide_index.py, python/python/tests/test_embeddings.py, python/python/tests/test_table.py, python/python/tests/test_util.py
BREAKING CHANGE: For a field "vector", list of integers will now be converted to binary (uint8) vectors instead of f32 vectors. Use float values instead for f32 vectors.
* Adds proper support for inserting and upserting subsets of the full schema. I thought I had previously implemented this in #1827, but it turns out I had not tested carefully enough.
* Refactors `_santize_data` and other utility functions to be simpler and not require `numpy` or `combine_chunks()`.
* Added a new suite of unit tests to validate sanitization utilities.
```python
import pandas as pd
import lancedb
db = lancedb.connect("memory://demo")
intial_data = pd.DataFrame({
"a": [1, 2, 3],
"b": [4, 5, 6],
"c": [7, 8, 9]
})
table = db.create_table("demo", intial_data)
new_data = pd.DataFrame({"a": [10, 11]}) …
```
=> feat(python)!: support inserting and upserting subschemas

python/python/lancedb/query.py, python/python/tests/test_query.py
BREAKING CHANGE: prefiltering is now the default in the synchronous python SDK
resolves: #1872
=> feat!: change default from postfiltering to prefiltering for sync python

rust/lancedb/src/table.rs
Expose methods on NativeTable for updating schema metadata and dataset config & getting the dataset config via the manifest.
=> feat: expose dataset config

docs/src/guides/storage.md
In the sync code example there was also an `await`.
=> docs: update storage.md, fix Azure Sync connect example

Cargo.toml, python/pyproject.toml
Upstream changelog: https://github.com/lancedb/lance/releases/tag/v0.22.0
=> feat: upgrade Lance to v0.22.0

python/python/lancedb/rerankers/linear_combination.py, python/python/tests/test_rerankers.py
related to #2014 
this fixes:
- linear reranker may lost some results if the merging consumes all vector results earlier than fts results
- linear reranker inverts the fts score but only vector distance can be inverted
=> fix: linear reranker applies wrong score to combine

rust/lancedb/src/table.rs
When calling `replace_field_metadata` we pass in an iter of tuples `(u32, HashMap<String, String>)`.
That `u32` needs to be the field id from the lance schema
https://github.com/lancedb/lance/blob/7f60aa0a877e41fab188b7156ac4f14e767ba968/rust/lance-core/src/datatypes/field.rs#L123
This can sometimes be different than the index of the field in the arrow schema (e.g. if fields have been dropped).
This PR adds docs that try to clarify what that argument should be, as well as corrects the usage in the test (which was improperly passing the index of the arrow schema).
=> docs: clarify the arguments for `replace_field_metadata`

python/python/lancedb/query.py, python/python/tests/test_hybrid_query.py, python/python/tests/test_rerankers.py
Fixes #2031
When we do hybrid search, we normalize the scores. We do this calculation in-place, because the Rerankers expect the `_distance` and `_score` columns to be the normalized ones. So I've changed the logic so that we restore the original distance and scores by matching on row ids.
=> fix(python): preserve original distance and score in hybrid queries

nodejs/__test__/embedding.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/merge.ts, nodejs/lancedb/table.ts
* `createTable()` now saves embeddings in the schema metadata. Previously, it would drop them. (`createEmptyTable()` was already tested and worked.)
* `mergeInsert()` now uses embeddings.
Fixes #2066
=> fix(node): `createTable()` should save embeddings, and `mergeInsert` should use them

python/python/lancedb/query.py, python/python/tests/docs/test_binary_vector.py, python/python/tests/docs/test_search.py, python/python/tests/test_query.py, python/python/tests/test_remote_db.py, python/python/tests/test_table.py
This PR aims to fix #2047 by doing the following things:
- Add a distance_type parameter to the sync query builders of Python SDK.
- Make metric an alias to distance_type.
=> feat: add `distance_type()` parameter to python sync query builders and `metric()` as an alias

Cargo.toml, python/pyproject.toml
This includes several bugfixes for `merge_insert` and null handling in vector search.
https://github.com/lancedb/lance/releases/tag/v0.23.0-beta.3
=> feat: upgrade lance to v0.23.0-beta.3

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, rust/lancedb/Cargo.toml
* Adds a CI job to check the cross compiled Windows ARM build.
* Didn't replace the test build because we need native build to run tests. But for some reason (I forget why) we need cross compiled for nodejs.
* Pinned crunchy to workaround https://github.com/eira-fransham/crunchy/issues/13
This is needed to fix failure from https://github.com/lancedb/lancedb/actions/runs/13020773184/job/36320719331
=> ci: fix arm64 windows cross compile build

rust/lancedb/src/connection.rs, rust/lancedb/tests/embedding_registry_test.rs
Fix for: https://github.com/lancedb/lancedb/issues/1581
This is the same implementation as https://github.com/lancedb/lancedb/pull/1781 but with the addition of a unit test and rustfmt.
=> fix(rust): add embedding_registry on open_table

Cargo.lock, Cargo.toml, python/pyproject.toml
Upstream changelog: https://github.com/lancedb/lance/releases/tag/v0.23.0-beta.4
=> feat: upgrade lance to 0.23.0-beta.4

.pre-commit-config.yaml, Cargo.lock, docs/src/js/interfaces/CreateTableOptions.md, nodejs/__test__/connection.test.ts, nodejs/lancedb/connection.ts, nodejs/src/connection.rs, python/.gitignore, python/python/lancedb/_lancedb.pyi, python/python/lancedb/db.py, python/python/lancedb/table.py, python/python/tests/test_db.py, python/src/connection.rs, rust/lancedb/src/catalog.rs, rust/lancedb/src/catalog/listing.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/database.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/query.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/table.rs
This opens up the door for more custom database implementations than the two we have today.  The biggest change should be inivisble:  `ConnectionInternal` has been renamed to `Database`, made public, and refactored
However, there are a few breaking changes.  `data_storage_version` and `enable_v2_manifest_paths` have been moved from options on `create_table` to options for the database which are now set via `storage_options`.
Before:
```
db = connect(uri)
tbl = db.create_table("my_table", data, data_storage_version="legacy", enable_v2_manifest_paths=True)
```
After:
```
db = connect(uri, storage_options={
"new_table_enable_v2_manifest_paths": "true",
"new_table_data_storage_version": "legacy"
})
tbl = db.create_table("my_table", data)
```
BREAKING CHANGE: the data_storage_version, …
=> feat!: refactor ConnectionInternal into a Database trait

Cargo.lock, docs/src/js/interfaces/ClientConfig.md, nodejs/__test__/remote.test.ts, nodejs/src/remote.rs, python/python/lancedb/remote/__init__.py, python/python/tests/test_remote_db.py, python/src/connection.rs, rust/lancedb/src/remote/client.rs
Closes #1106
Unfortunately, these need to be set at the connection level. I investigated whether if we let users provide a callback they could use `AsyncLocalStorage` to access their context. However, it doesn't seem like NAPI supports this right now. I filed an issue: https://github.com/napi-rs/napi-rs/issues/2456
=> feat: extra headers parameter in client options

docs/src/js/classes/Connection.md, nodejs/__test__/connection.test.ts, nodejs/lancedb/connection.ts, nodejs/src/connection.rs, python/python/lancedb/db.py, python/python/tests/test_db.py, python/src/connection.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/database.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/remote/db.rs
If we start supporting external catalogs then "drop database" may be misleading (and not possible).  We should be more clear that this is a utility method to drop all tables.  This is also a nice chance for some consistency cleanup as it was `drop_db` in rust, `drop_database` in python, and non-existent in typescript.
This PR also adds a public accessor to get the database trait from a connection.
BREAKING CHANGE: the `drop_database` / `drop_db` methods are now deprecated.
=> refactor: rename drop_db / drop_database to drop_all_tables, expose database from connection

rust/lancedb/src/table.rs
panicked at 'index out of bounds: the len is 24 but the index is 25':Lancedb/rust/lancedb/src/index/vector.rs:26\n
load_indices() on the old manifest while use the newer manifest to get column names could result in index out of bound if some columns are removed from the new version.
This change reduce the possibility of index out of bound operation but does not fully remove it.
Better that lance can directly provide column name info so no need extra calls to get column name but that require modify the public APIs
=> fix: fix index out of bound in load indices

Cargo.lock, python/python/tests/test_query.py
we found a bug that flat KNN plan node's stats is not in right order as fields in schema, it would cause an error if querying with distance range and new unindexed rows.
we've fixed this in lance so add this test for verifying it works
=> test: query with dist range and new rows

docs/src/python/polars_arrow.md, python/python/lancedb/table.py, python/python/tests/docs/test_binary_vector.py, python/python/tests/docs/test_distance_range.py, python/python/tests/docs/test_embeddings_optional.py, python/python/tests/docs/test_guide_index.py, python/python/tests/docs/test_python.py, python/python/tests/docs/test_search.py, python/python/tests/test_query.py, python/python/tests/test_remote_db.py, python/python/tests/test_rerankers.py
Reviving #1966.
Closes #1938
The `search()` method can apply embeddings for the user. This simplifies hybrid search, so instead of writing:
```python
vector_query = embeddings.compute_query_embeddings("flower moon")[0]
await (
async_tbl.query()
.nearest_to(vector_query)
.nearest_to_text("flower moon")
.to_pandas()
)
```
You can write:
```python
await (await async_tbl.search("flower moon", query_type="hybrid")).to_pandas()
```
Unfortunately, we had to do a double-await here because `search()` needs to be async. This is because it often needs to do IO to retrieve and run an embedding function.
=> feat(python): add search() method to async API

docs/mkdocs.yml, docs/src/embeddings/custom_embedding_function.md, docs/src/embeddings/variables_and_secrets.md, docs/src/js/namespaces/embedding/classes/EmbeddingFunction.md, docs/src/js/namespaces/embedding/classes/EmbeddingFunctionRegistry.md, docs/src/js/namespaces/embedding/classes/TextEmbeddingFunction.md, nodejs/__test__/embedding.test.ts, nodejs/__test__/registry.test.ts, nodejs/__test__/table.test.ts, nodejs/examples/embedding.test.ts, nodejs/lancedb/embedding/embedding_function.ts, nodejs/lancedb/embedding/openai.ts, nodejs/lancedb/embedding/registry.ts, nodejs/lancedb/embedding/transformers.ts, python/python/lancedb/embeddings/base.py, python/python/lancedb/embeddings/jinaai.py, python/python/lancedb/embeddings/openai.py, python/python/lancedb/embeddings/registry.py, python/python/lancedb/embeddings/watsonx.py, python/python/tests/docs/test_embeddings_optional.py, python/python/tests/test_embeddings.py, python/python/tests/test_rerankers.py, python/python/tests/test_table.py, python/python/tests/test_util.py
BREAKING CHANGE: embedding function implementations in Node need to now call `resolveVariables()` in their constructors and should **not** implement `toJSON()`.
This tries to address the handling of secrets. In Node, they are currently lost. In Python, they are currently leaked into the table schema metadata.
This PR introduces an in-memory variable store on the function registry. It also allows embedding function definitions to label certain config values as "sensitive", and the preprocessing logic will raise an error if users try to pass in hard-coded values.
Closes #2110
Closes #521
=> feat!: add variable store to embeddings registry

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, python/pyproject.toml
This also changes the pylance pin from `==0.23.2` to `~=0.23.2` which should allow the pylance dependency to float a little.  The pylance dependency is actually not used for much anymore and so it should be tolerant of patch changes.
=> feat: upgrade lance to 0.23.2

nodejs/__test__/table.test.ts, python/python/lancedb/query.py, python/python/lancedb/table.py, python/python/tests/test_fts.py, python/python/tests/test_table.py, rust/lancedb/src/query.rs, rust/lancedb/src/remote/table.rs
In earlier PRs (#1886, #1191) we made the default limit 10 regardless of the query type. This was confusing for users and in many cases a breaking change. Users would have queries that used to return all results, but instead only returned the first 10, causing silent bugs.
Part of the cause was consistency: the Python sync API seems to have always had a limit of 10, while newer APIs (Python async and Nodejs) didn't.
This PR sets the default limit only for searches (vector search, FTS), while letting scans (even with filters) be unbounded. It does this consistently for all SDKs.
Fixes #1983
Fixes #1852
Fixes #2141
=> feat!: revert query limit to be unbounded for scans

Cargo.lock, rust/lancedb/src/table/datafusion.rs
It seems that `RecordBatch::with_schema` is unable to remove schema metadata from a batch.  It fails with the error `target schema is not superset of current schema`.
I'm not sure how the `test_metadata_erased` test is passing.  Strangely, the metadata was not present by the time the batch arrived at the metadata eraser.  I think maybe the schema metadata is only present in the batch if there is a filter.
I've created a new unit test that makes sure the metadata is erased if we have a filter also
=> fix: don't use with_schema to remove schema metadata

rust/lancedb/src/arrow.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/database.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/table.rs
This PR makes it possible to create a table using an asynchronous stream of input data.  Currently only a synchronous iterator is supported.  There are a number of follow-ups not yet tackled:
* Support for embedding functions (the embedding functions wrapper needs to be re-written to be async, should be an easy lift)
* Support for async input into the remote table (the make_ipc_batch needs to change to accept async input, leaving undone for now because I think we want to support actual streaming uploads into the remote table soon)
* Support for async input into the add function (pretty essential, but it is a fairly distinct code path, so saving for a different PR)
=> feat: add support for streaming input to create_table

Cargo.lock, rust/lancedb/src/table/datafusion.rs
Datafusion makes the batch size available as part of the `SessionState`.  We should use that to set the `max_batch_length` property in the `QueryExecutionOptions`.
=> feat: respect datafusion's batch size when running as a table provider

nodejs/__test__/s3_integration.test.ts, python/Makefile, python/python/tests/test_s3.py, rust/lancedb/src/database/listing.rs
Prior to this commit, issuing drop_all_tables on a listing database with an external manifest store would delete physical tables but leave references behind in the manifest store. The table drop would succeed, but subsequent creation of a table with the same name would fail with a conflict.
With this patch, the external manifest store is updated to account for the dropped tables so that dropped table names can be reused.
=> fix: delete tables from DDB on drop_all_tables

python/pyproject.toml
We attempted to make pylance optional in https://github.com/lancedb/lancedb/pull/2156 but it appears this did not quite work.  Users are unable to use lancedb from a fresh install.  This reverts the optional-ness so we can get back in a working state while we fix the issue.
=> fix: restore pylance as mandatory dependency

python/python/lancedb/embeddings/base.py
Hello LanceDB team,
---
I have fixed a discrepancy in the class docstring of `lancedb.embeddings.base:EmbeddingFunction` and made consistency alignments to that docstring.
1. The docstring referred to the abstract method `get_source_embeddings()`.
This method does not exist in the repository at the current state.
I have changed the mention to refer to the actual abstract method `compute_source_embeddings()`.
2. Also, I aligned the consistency within the ordered list which is describing the methods to be implemented by concrete embedding functions.
---
Thank you for developing this useful library. 👍
Best regards
Martin
=> docs: fix docstring of EmbeddingFunction

Cargo.lock, docs/src/guides/tables.md, docs/src/js/interfaces/ColumnAlteration.md, nodejs/__test__/table.test.ts, nodejs/examples/basic.test.ts, nodejs/lancedb/arrow.ts, nodejs/lancedb/index.ts, nodejs/lancedb/table.ts, python/python/tests/docs/test_basic.py, rust/lancedb/src/utils.rs
Previously, users could only specify new data types in `alterColumns` as strings:
```ts
await tbl.alterColumns([
path: "price",
dataType: "float"
]);
```
But this has some problems:
1. It wasn't clear what were valid types
2. It was impossible to specify nested types, like lists and vector columns.
This PR changes it to take an Arrow data type, similar to how the Python API works. This allows casting vector types:
```ts
await tbl.alterColumns([
{
path: "vector",
dataType: new arrow.FixedSizeList(
2,
new arrow.Field("item", new arrow.Float16(), false),
),
},
]);
```
Closes #2185
=> feat(node): parse arrow types in `alterColumns()`

python/python/lancedb/query.py
Hello LanceDB team,
while developing using `lancedb` as a library I encountered a typing problem affecting IDE hints and completions during development.
---
Currently, the abstract base class `lancedb.query:LanceQueryBuilder` uses method chaining to build up the search parameters, where the methods have `LanceQueryBuilder` as a return type hint.
This leads to two issues:
1. Implementing subclasses of `LanceQueryBuilder` need to override methods to modify the return type hint, even when they don't need to change its implementation, just to ensure adequate IDE hints and completions.
2. When using method chaining the first method directly inherited from the abstract `LanceQueryBuilder` causes the inferred type to switch back to `LanceQueryBuilder`. So even when the type starts from …
=> fix: use Self return type annotation for abstract query builder

python/python/lancedb/table.py, python/python/tests/test_table.py
Closes #2114
Starting in #1965, we no longer pass the table schema into `pa.Table.from_pylist()`. This means PyArrow is choosing the order of the struct subfields, and apparently it does them in alphabetical order. This is fine in theory, since in Lance we support providing fields in any order. However, before we pass it to Lance, we call `pa.Table.cast()` to align column types to the table types. `pa.Table.cast()` is strict about field order, so we need to create a cast target schema that aligns with the input data. We were doing this at the top-level fields, but weren't doing this in nested fields. This PR adds support to do this for nested ones.
=> fix: insert structs in non-alphabetical order

rust/lancedb/src/catalog/listing.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/remote.rs, rust/lancedb/src/remote/db.rs
The `ConnectRequest` has a set of properties that only make sense for listing databases / catalogs and a set of properties that only make sense for remote databases.
This PR reduces all options to a single `HashMap<String, String>`.  This makes it easier to add new database / catalog implementations and makes it clearer to users which options are applicable in which situations.
I don't believe there are any breaking changes here.  The closest thing is that I placed the `ConnectBuilder` methods `api_key`, `region`, and `host_override` behind a `remote` feature gate.  This is not strictly needed and I could remove the feature gate but it seemed appropriate.  Since using these methods without the remote feature would have been meaningless I don't feel this counts as a breaking change.
We …
=> refactor: rework catalog/database options

docs/mkdocs.yml, docs/src/examples/index.md, docs/src/index.md
2/2 docs update this week
- Add cloud & enterprise CTA
- remove outdated projects/examples from landing page
=> docs: add cloud & enterprise cta

.bumpversion.toml, .github/workflows/npm-publish.yml, node/package-lock.json, node/package.json
vectordb is deprecated, and these platforms are particularly difficult to maintain. Removing now to prevent further headaches.
We will keep these platforms supported on `@lancedb/lancedb`.
=> ci: drop vectordb support for musl, windows ARM

rust/lancedb/src/lib.rs
I'm pretty sure you mean `cargo add lancedb` here, `cargo install lancedb` fails right now.
=> fix: correct rust install docs

.github/workflows/pypi-publish.yml
This just makes it easier to test in the future.
=> ci: allow dry run on PR to Python release

docs/src/cloud/index.md, docs/src/guides/tables.md, docs/src/index.md
* direct users to cloud.lancedb.com since LanceDB Cloud is in public beta
* removed the `cast vector dimension` from alter columns as we don't support it
=> docs: replace Lancedb Cloud link

python/python/lancedb/rerankers/answerdotai.py
This fixes an issue for people wishing to use different kinds of rerankers in lancedb via AnswerDotAI rerankers. Currently, the arguments are passed sequentially, but they don't match the[Reranker class implementation](https://github.com/AnswerDotAI/rerankers/blob/d604a8c47d7a9fce1b6ef0cec53f0e807d6cc0fa/rerankers/reranker.py#L179): the second argument is expected to be an optional "lang" for default models, while model_type should be passed explicitly. 
The one line changes in this PR fixes it and enables the use of other methods (eg LLMs-as-rerankers)
=> fix: answerdotai rerankers argument passing

docs/src/guides/tables.md, docs/src/js/interfaces/ConnectionOptions.md, docs/src/troubleshooting.md, node/src/integration_test/test.ts, nodejs/__test__/connection.test.ts, nodejs/__test__/table.test.ts, nodejs/examples/basic.test.ts, nodejs/src/connection.rs, nodejs/src/lib.rs, python/python/lancedb/__init__.py, python/python/lancedb/db.py, python/python/tests/docs/test_guide_tables.py, python/python/tests/test_db.py, python/python/tests/test_table.py, python/src/connection.rs, rust/ffi/node/src/lib.rs, rust/lancedb/src/catalog/listing.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/table.rs, rust/lancedb/src/table/dataset.rs
Previously, when we loaded the next version of the table, we would block all reads with a write lock. Now, we only do that if `read_consistency_interval=0`. Otherwise, we load the next version asynchronously in the background. This should mean that `read_consistency_interval > 0` won't have a meaningful impact on latency.
Along with this change, I felt it was safe to change the default consistency interval to 5 seconds. The current default is `None`, which means we will **never** check for a new version by default. I think that default is contrary to most users expectations.
=> feat!: change default read_consistency_interval=5s

rust/lancedb/src/remote/table.rs
Fix restore to always checkout latest version, following local restore api implementation 
https://github.com/lancedb/lancedb/blob/a1d1833a40eb03f83a00921279652c36e4836e9c/rust/lancedb/src/table.rs#L1910
Otherwise
table.create_table -> version 1
table.add_table -> version 2
table.checkout(1), table.restore() -> the version remains at 1  (should checkout_latest inside restore method to update version to latest version and allow write operation)
table.checkout_latest() -> version is 3
can do write operations
=> fix: fix remote restore api to always checkout latest version

.github/workflows/npm-publish.yml
I released each time we published, the new package was no longer deprecated. This re-deprecated the package after a new publish.
=> ci: deprecate vectordb each release

Cargo.lock, python/src/query.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/data/inspect.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/rerankers.rs, rust/lancedb/src/table.rs
=> chore: fix 1.86 warnings

rust/lancedb/src/catalog/listing.rs
this PR is to expose the error from `ListingCatalog::open_path` which unwrap the Result coming from `ObjectStore::from_uri` to avoid panic
=> fix: expose parsing error coming from invalid object store uri

rust/lancedb/src/table/dataset.rs
Make sure we only update the latest version if it's actually newer. This is important if there are concurrent queries, as they can take different amounts of time.
=> fix: only monotonically update dataset

python/python/lancedb/remote/table.py, python/python/tests/test_remote_db.py
just noticed that we're doing a 'return' instead of a 'raise' while trying to get remote functionality working for my project. I went ahead and implemented tests for both of the unimplemented functions (to_pandas and to_arrow) while I was in there.
=> fix: change 'return' to 'raise' for unimplemented remote table function

nodejs/lancedb/table.ts
Thanks for all your work.
The docstring for `OptimizeOptions ` seems to reference a non-existent method on `Table`. I believe this is the correct example for `cleanupOlderThan`.
This also appears in the generated docs, but I assume they live downstream from this code?
=> chore: fix cleanupOlderThan docs

python/python/lancedb/query.py, python/python/lancedb/rerankers/answerdotai.py, python/python/lancedb/rerankers/base.py, python/python/lancedb/rerankers/cohere.py, python/python/lancedb/rerankers/cross_encoder.py, python/python/lancedb/rerankers/jinaai.py, python/python/lancedb/rerankers/openai.py, python/python/lancedb/rerankers/voyageai.py, python/python/tests/test_rerankers.py
Previously `return_score="all"` was supported only for the default reranker (RRF) and not the model based rerankers.
This adds support for keeping all scores in the base reranker so that all model based rerankers can use it. Its a slower path than keeping just the relevance score but can be useful in debugging
=> feat: add support for returning all scores with rerankers

Cargo.lock, rust/lancedb/src/database/listing.rs, rust/lancedb/tests/object_store_test.rs
This fixes two bugs with create_table storage handle reuse. First issue is, the database object did not previously carry a session that create_table operations could reuse for create_table operations.
Second issue is, the inheritance logic for create_table and open_table was causing empty storage options (i.e Some({})) to get sent, instead of None. Lance handles these differently:
* When None is set, the object store held in the session's storage registry that was created at "connect" is used. This value stays in the cache long-term (probably as long as the db reference is held).
* When Some({}) is sent, LanceDB will create a new connection and cache it for an empty key. However, that cached value will remain valid only as long as the client holds a reference to the table. After that, the …
=> fix: excessive object storage handle creation in create_table

python/python/tests/test_query.py
this test adds a new vector and then performs vector search with distance range.
this may fail if the new vector becomes the closest one to the query vector
=> test: fix random data may break test case

.github/workflows/cargo-publish.yml
This PR will enable trust publishing for all our rust crates. After this change, we don't need to have static key from crates.io anymore.
=> ci: enable trust publishing for rust crates

python/python/lancedb/embeddings/gte_mlx_model.py, python/python/lancedb/embeddings/utils.py, python/python/lancedb/query.py, python/python/tests/test_hybrid_query.py, python/python/tests/test_query.py
- Add `create_import_stub()` helper to `embeddings/utils.py` for handling optional dependencies
- Fix MLX doctest collection failures by using import stubs in `gte_mlx_model.py`
- Module now imports successfully for doctest collection even when MLX is not installed
- **New utility function**: `create_import_stub()` creates placeholder objects that allow class inheritance but raise helpful errors when used
- **Updated MLX model**: Uses import stubs instead of direct imports that fail immediately
- **Graceful degradation**: Clear error messages when MLX functionality is accessed without MLX installed
- ✅ `pytest --doctest-modules python/lancedb` now passes (with and without MLX installed)
- ✅ All existing tests continue to pass
- ✅ MLX functionality works normally when MLX is installed
- ✅ …
=> fix: use import stubs to prevent MLX doctest collection failures

python/python/lancedb/__init__.py
Fixed a minor grammar error in the error message for missing API key when connecting to LanceDB cloud.
- Changed 'api_key is required to connected LanceDB cloud' to 'api_key is required to connect to LanceDB cloud'
- Location: `python/python/lancedb/__init__.py:95`
- Error message formatting is correct and grammatical
- No functional changes to existing behavior
=> fix: correct grammar in LanceDB cloud connection error message

python/python/tests/test_fts.py
Fixes intermittent CI failures in `test_search_fts[False]` where boolean FTS queries were returning fewer results than expected due to non-deterministic test data generation.
The test was using global `random` and `np.random` without seeding, causing the boolean query `MatchQuery("puppy", "text") & MatchQuery("runs", "text")` to sometimes return only 3 results instead of the expected 5, leading to `AssertionError: assert 3 == 5`.
- Replace global random calls with local `random.Random(42)` and `np.random.RandomState(42)` objects in test fixtures
- Ensures deterministic test data while maintaining test isolation
- No impact on other tests since random state is scoped to fixtures only
- ✅ `test_search_fts[False]` now passes consistently
- ✅ All other FTS tests continue to pass 
- ✅ No …
=> fix: use local random state in FTS test fixtures to prevent flaky failures

node/src/integration_test/test.ts
- Fixed flaky Node.js integration test for mirrored store functionality
- Converted callback-based `fs.readdir()` to `fs.promises.readdir()` with proper async/await
- Used unique temporary directories to prevent test isolation issues
- Updated test expectations to match current IVF-PQ index file structure
The mirrored store integration test was experiencing random failures in CI with errors like:
- `expected 2 to equal 1` at various assertion points
- `done() called multiple times`
1. **Race conditions**: Mixing callback-based filesystem operations with async functions created timing issues where assertions ran before filesystem operations completed
2. **Test isolation**: Multiple tests shared the same temp directory (`tmpdir()`), causing one test to see files from another
3. **Outdated …
=> fix: resolve flaky Node.js integration test for mirrored store

python/python/lancedb/common.py, python/python/lancedb/table.py
Replaces broken 404 URL and unhelpful documentation links in type error messages with working URL and inline list of supported data types.
**Before**: Points to https://lancedb.github.io/lance/read_and_write.html (404 error)  
**After**: Lists supported types inline and points to https://lancedb.github.io/lancedb/guides/tables/
=> fix: replace broken documentation URLs in error messages

rust/lancedb/src/table/datafusion.rs
The `MetadataEraserExec` is super lightweight and doesn't really justify partitioning.  I had a plan recently that was partitioning just for this node and that seems wasteful.
=> feat: don't repartition for the sake of the metadata eraser

nodejs/__test__/table.test.ts, python/python/lancedb/table.py, python/python/tests/test_query.py, rust/lancedb/src/query.rs
`nprobes` with a value greater than 20 fails with the minimum error:
```
self = <lancedb.query.AsyncVectorQuery object at 0x10b749720>, minimum_nprobes = 30
def minimum_nprobes(self, minimum_nprobes: int) -> Self:
"""Set the minimum number of probes to use.
See `nprobes` for more details.
These partitions will be searched on every indexed vector query and will
increase recall at the expense of latency.
"""
>       self._inner.minimum_nprobes(minimum_nprobes)
E       ValueError: Invalid input, minimum_nprobes must be less than or equal to maximum_nprobes
python/lancedb/query.py:2744: ValueError
```
Putting the max set before the min seems reasonable but it causes this reasonable case to fail:
```
def test_nprobes_min_max_works_sync(table):
LanceVectorQueryBuilder(table, [0, 0], …
```
=> fix: `.nprobes` method in python bindings, improve error messages

nodejs/examples/package-lock.json, nodejs/npm/darwin-arm64/package.json, nodejs/npm/darwin-x64/package.json, nodejs/npm/linux-arm64-gnu/package.json, nodejs/npm/linux-arm64-musl/package.json, nodejs/npm/linux-x64-gnu/package.json, nodejs/npm/linux-x64-musl/package.json, nodejs/npm/win32-arm64-msvc/package.json, nodejs/npm/win32-x64-msvc/package.json, nodejs/package-lock.json, nodejs/package.json
Update license field from `Apache 2.0` to be `Apache-2.0` for all Node.js packages.
This was causing GitHub's Dependency Review license check to fail with:
> The validity of the licenses of the dependencies below could not be determined. Ensure that they are valid SPDX licenses
=> fix: use SPDX-compliant license name for nodejs packages

CLAUDE.md, docs/src/js/classes/Session.md, docs/src/js/interfaces/IndexOptions.md, docs/src/js/interfaces/TimeoutConfig.md, nodejs/__test__/table.test.ts, nodejs/lancedb/indices.ts, nodejs/lancedb/table.ts, nodejs/src/table.rs, python/python/lancedb/_lancedb.pyi, python/python/lancedb/remote/table.py, python/python/lancedb/table.py, python/python/tests/test_table.py, python/src/table.rs, rust/lancedb/src/index.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs
Enables two new parameters when building indices:
* `name`: Allows explicitly setting a name on the index. Default is `{col_name}_idx`.
* `train` (default `True`): When set to `False`, an empty index will be immediately created.
The upgrade of Lance means there are also additional behaviors from https://github.com/lancedb/lance/commit/cd76a993b8b65877135cb9cfb47448a761ac7f7b:
* When a scalar index is created on a Table, it will be kept around even if all rows are deleted or updated.
* Scalar indices can be created on empty tables. They will default to `train=False` if the table is empty.
=> feat: allow setting `train=False` and `name` on indices

Cargo.toml, ci/set_lance_version.py, java/core/lancedb-jni/Cargo.toml, nodejs/Cargo.toml, python/Cargo.toml, rust/lancedb/Cargo.toml, rust/lancedb/src/connection.rs
This shrinks the size of a local embedded build that can disable all the default features. When combined with https://github.com/lancedb/lance/pull/4362 and the dependencies are updated to point to the fix, this resolves #2567 fully.
Verified by patching the workspace to redirect to my clone of lance with the PR applied.
```
cargo tree -p lancedb -e no-build -e no-dev --no-default-features -i aws-config | less
```
The reason that lance itself needs to change too is that many dependencies within that project depend on lance-io/default and lancedb depends on them which transitively ends up enabling the cloud regardless. The PR in lance removes the dependency on lance-io/default from all sibling crates.
=> fix: make cloud features optional (#2567)

Cargo.lock, Cargo.toml
Change logs:
* [v0.33.0-beta.3](https://github.com/lancedb/lance/releases/tag/v0.33.0-beta.3)
* [v0.33.0-beta.2](https://github.com/lancedb/lance/releases/tag/v0.33.0-beta.2)
* [v0.33.0-beta.1](https://github.com/lancedb/lance/releases/tag/v0.33.0-beta.1)
Important changes:
* Row-level conflict resolution for delete operations
* Fixes #2593
* Fix for keeping tombstones fields around, preventing cleanup of dropped columns.
=> feat: upgrade lance to 0.33.0-beta.3

python/pyproject.toml, python/python/lancedb/__init__.py, python/python/lancedb/namespace.py, python/python/tests/test_namespace.py
This PR integrates `lancedb` with `lance-namespace` so that users can use LanceDB client to access Lance tables in any catalog services. In general, we expect most of the logic to be delegated to the existing `LanceDBConnection` and `LanceTable`, but the namespace implemenation will control how table is created, dropped, and describe where the table is stored with any related storage options like access credentials.
The implementation currently only supports a 1 level namespace that directly contains tables. We will introduce nested namespace support in a separated PR.
Users are expected to use it in the following way:
```python
>>> import lancedb
>>> import pyarrow as pa
>>> # Connect using GlueNamespace
>>> db = lancedb.connect_namespace("glue", {"catalog_id": "123456789012"})
>>> # …
```
=> feat(python): integrate with lance namespace

nodejs/lancedb/connection.ts, nodejs/src/connection.rs, nodejs/src/remote.rs, python/python/lancedb/_lancedb.pyi, python/python/lancedb/db.py, python/python/lancedb/namespace.py, python/python/lancedb/remote/__init__.py, python/python/lancedb/remote/db.py, python/python/lancedb/table.py, python/python/tests/test_db.py, python/python/tests/test_namespace.py, python/src/connection.rs, rust/lancedb/examples/simple.rs, rust/lancedb/src/catalog/listing.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/database.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/remote/client.rs, rust/lancedb/src/remote/db.rs, rust/lancedb/src/remote/table.rs, rust/lancedb/src/table.rs, rust/lancedb/tests/object_store_test.rs
This PR adds support of multi-level namespace in a LanceDB database, according to the Lance Namespace spec.
This allows users to create namespace inside a database connection, perform create, drop, list, list_tables in a namespace. (other operations like update, describe will be in a follow-up PR)
The 3 types of database connections behave like the following:
1 Local database connections will continue to have just a flat list of tables for backwards compatibility.
2. Remote database connections will make REST API calls according to the APIs in the Lance Namespace spec. 
3. Lance Namespace connections will invoke the corresponding operations against the specific namespace implementation which could have different behaviors regarding these APIs.
All the table APIs now take identifier …
=> feat!: support multi-level namespace

python/python/lancedb/db.py, python/python/lancedb/namespace.py, python/python/lancedb/remote/db.py, python/python/tests/test_db.py, python/python/tests/test_namespace.py
This changes the default values for some namespace parameters in the remote python SDK from None to [], to match the underlying code it calls.
Prior to this commit, failing to supply "namespace" with the remote SDK would cause an error because the underlying code it dispatches to does not consider None to be valid input.
=> fix: remote python sdk namespace typing

nodejs/__test__/embedding.test.ts, nodejs/lancedb/arrow.ts
- Fixes issue where passing `{ vector: undefined }` with an embedding function threw "Found field not in schema" error instead of calling the embedding function like `null` or omitted fields.
**Changes:**
- Modified `rowPathsAndValues` to skip undefined values during schema inference
- Added test case verifying undefined, null, and omitted vector fields all work correctly
**Before:** `{ vector: undefined }` → Error
**After:** `{ vector: undefined }` → Calls embedding function
Closes #2647
=> fix(node): handle undefined vector fields with embedding functions

nodejs/__test__/connection.test.ts, nodejs/lancedb/connection.ts, nodejs/src/connection.rs, python/python/lancedb/_lancedb.pyi, python/python/lancedb/db.py, python/python/lancedb/remote/db.py, python/python/tests/test_db.py, python/src/connection.rs, rust/lancedb/src/connection.rs, rust/lancedb/src/database.rs, rust/lancedb/src/database/listing.rs, rust/lancedb/src/remote/db.rs
Support shallow cloning a dataset at a specific location to create a new dataset, using the shallow_clone feature in Lance. Also introduce remote `clone` API for remote tables for this functionality.
=> feat: support shallow clone

.github/workflows/rust.yml, Cargo.lock, ci/create_lancedb_test_connection.sh, ci/run_with_docker_compose.sh, ci/run_with_test_connection.sh, rust/lancedb/Cargo.toml, rust/lancedb/Makefile, rust/lancedb/src/connection.rs, rust/lancedb/src/lib.rs, rust/lancedb/src/test_connection.rs
Add a new test feature which allows for running the lancedb tests against a remote server. Convert over a few tests in src/connection.rs as a proof of concept.
To make local development easier, the remote tests can be run locally from a Makefile. This file can also be used to run the feature tests, with a single invocation of 'make'. (The feature tests require bringing up a docker compose environment.)
=> feat: add support for test_remote_connections

python/pyproject.toml, python/python/lancedb/db.py, python/python/lancedb/namespace.py, python/python/lancedb/remote/db.py
Fixes #2698  
This PR uses [`typing.override`](https://docs.python.org/3/library/typing.html#typing.override) in favor of the [`overrides`](https://pypi.org/project/overrides/) dependency when possible. As of Python 3.12, the standard library offers `typing.override` to perform a static check on overridden methods. 
Currently, `overrides` is incompatible with Python 3.14. As a result, any package that attempts to import `overrides` using Python 3.14+ will raise an `AttributeError`. An [issue](https://github.com/mkorpela/overrides/issues/127) has been raised and a [pull request](https://github.com/mkorpela/overrides/pull/133) has been submitted to the GitHub repo for the `overrides` project. But the maintainer has been unresponsive.
To ensure readiness for Python 3.14, this package (and …
=> fix: use stdlib override when possible
